import { useEffect, useRef, useState } from "react";
const KEY="cookie-consent-v2", defaults={necessary:true,analytics:false,personalization:false};
const options=[["necessary","Essential","Security, authentication, and privacy choices.",true],["analytics","Analytics","Anonymous insights that help us improve Banner."],["personalization","Personalization","Content and recommendations tailored to you."]];
const products=[["Plan","Shape ideas into clear briefs, roadmaps, and milestones.","01"],["Create","Write, review, and organize every piece of work together.","02"],["Align","Keep decisions, feedback, and progress visible to everyone.","03"]];
const team=[["AM","Amara Miles","Co-founder · Product"],["JL","Jonah Lee","Co-founder · Engineering"],["SK","Sofia Khan","Design Director"]];
function read(){try{const v=localStorage.getItem(KEY);return v?JSON.parse(v):null}catch{return null}}
export default function App(){
 const [consent,setConsent]=useState(read),[open,setOpen]=useState(false),[draft,setDraft]=useState(defaults),[selected,setSelected]=useState(0);const modal=useRef();
 const save=p=>{const value={...p,necessary:true,updatedAt:new Date().toISOString()};try{localStorage.setItem(KEY,JSON.stringify(value))}catch{}setConsent(value);setOpen(false)};
 const manage=()=>{setDraft(consent||defaults);setOpen(true)};
 useEffect(()=>{if(!open)return;const old=document.activeElement;modal.current?.focus();const esc=e=>e.key==="Escape"&&setOpen(false);document.addEventListener("keydown",esc);return()=>{document.removeEventListener("keydown",esc);old?.focus()}},[open]);
 return <main>
  <nav><a className="brand" href="#top"><b>B</b> Banner</a><div><a href="#product">Product</a><a href="#company">Company</a><button onClick={manage}>Privacy settings</button></div></nav>
  <section className="hero" id="top"><small><i/> DESIGNED WITH PRIVACY IN MIND</small><h1>Your ideas deserve<br/><em>room to grow.</em></h1><p>Banner is the calm, collaborative workspace where ambitious teams turn early thoughts into meaningful work.</p><aside><a href="#product">Explore the product →</a><a href="#company">Meet our team</a></aside><div className="mock"><span/><article><small>PROJECT / AUTUMN LAUNCH</small><h3/><p/><p/><div><i/><i/><i/></div></article></div></section>
  <section className="products" id="product"><header><small>THE PRODUCT</small><h2>One place for work<br/><em>that matters.</em></h2><p>Move from first thought to final delivery without losing the context that makes your work meaningful.</p></header><div className="product-grid">{products.map(([title,description,number],index)=><button className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={title}><small>{number}</small><h3>{title}</h3><p>{description}</p><span>{selected===index?"Currently exploring":"Explore"} →</span></button>)}</div><div className="product-detail" aria-live="polite"><div><small>WORKFLOW · {products[selected][0].toUpperCase()}</small><h3>{products[selected][0]} with clarity.</h3><p>{products[selected][1]} Everything stays connected, searchable, and easy to share.</p></div><div className="detail-art"><i/><i/><i/></div></div></section>
  <section className="company" id="company"><header><small>THE PEOPLE</small><h2>Small team.<br/><em>Big care.</em></h2><p>We are designers, engineers, and hopeful pragmatists building calmer tools for thoughtful teams.</p></header><div className="team-grid">{team.map(([initials,name,role],index)=><article key={name}><div className={"avatar tone-"+index}>{initials}</div><h3>{name}</h3><p>{role}</p><a href={"mailto:"+name.toLowerCase().replace(" ",".")+"@banner.example"}>Say hello ↗</a></article>)}</div></section>
  <footer className="site-footer"><a className="brand" href="#top"><b>B</b> Banner</a><p>Thoughtful work starts here.</p><button onClick={manage}>Cookie preferences</button></footer>
  {consent&&<button className="privacy" onClick={manage}>◉ &nbsp;Privacy</button>}
  {!consent&&<section className="banner" role="dialog" aria-labelledby="cookie-title"><div className="cookie">•••</div><article><h2 id="cookie-title">A thoughtful cookie choice</h2><p>We use essential cookies to keep Banner working. With your permission, we’d also like optional cookies to understand what’s useful and personalize your experience. <a href="#policy">Read our cookie policy</a>.</p></article><footer><button className="primary" onClick={()=>save({necessary:true,analytics:true,personalization:true})}>Accept all</button><button onClick={()=>save(defaults)}>Reject optional</button><button className="link" onClick={manage}>Manage preferences</button></footer></section>}
  {open&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="prefs-title" tabIndex="-1" ref={modal}><button className="close" aria-label="Close" onClick={()=>setOpen(false)}>×</button><small>PRIVACY CENTER</small><h2 id="prefs-title">Choose what works for you</h2><p>Essential cookies are always active. Everything else is entirely your choice.</p><div className="list">{options.map(([key,title,description,locked])=><article key={key}><div><b>{title}</b>{locked&&<mark>Always on</mark>}<p>{description}</p></div><button role="switch" aria-checked={draft[key]} aria-label={title} disabled={locked} className={"toggle "+(draft[key]?"on":"")} onClick={()=>setDraft(d=>({...d,[key]:!d[key]}))}><i/></button></article>)}</div><footer><button onClick={()=>save(defaults)}>Reject optional</button><button className="primary" onClick={()=>save(draft)}>Save my choices</button></footer></section></div>}
 </main>
}


