-- Run this entire file in the Supabase SQL editor before setting React env variables.
create extension if not exists "uuid-ossp";
create type public.app_role as enum ('admin', 'hod', 'coordinator', 'faculty');
create type public.allocation_status as enum ('allocated', 'unallocated', 'conflict');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, initials text, role app_role not null default 'faculty', created_at timestamptz not null default now());
create table public.programmes (id uuid primary key default uuid_generate_v4(), code text unique not null, name text not null);
create table public.faculty (id uuid primary key default uuid_generate_v4(), profile_id uuid unique references profiles(id) on delete set null, full_name text not null, initials text, employment_type text not null default 'permanent', max_credits integer not null default 12 check(max_credits > 0), expertise text[] not null default '{}');
create table public.courses (id uuid primary key default uuid_generate_v4(), code text unique not null, title text not null, credits integer not null check(credits between 1 and 6));
create table public.course_offerings (id uuid primary key default uuid_generate_v4(), course_id uuid not null references courses(id) on delete cascade, programme_id uuid not null references programmes(id), semester text not null, section text not null default 'A', unique(course_id, programme_id, semester, section));
create table public.allocations (id uuid primary key default uuid_generate_v4(), course_offering_id uuid unique not null references course_offerings(id) on delete cascade, faculty_id uuid not null references faculty(id), assigned_credits integer not null check(assigned_credits > 0), status allocation_status not null default 'allocated', created_at timestamptz not null default now());
create table public.conflicts (id uuid primary key default uuid_generate_v4(), course_offering_id uuid references course_offerings(id) on delete cascade, faculty_id uuid references faculty(id), kind text not null, message text not null, resolved boolean not null default false, created_at timestamptz not null default now(), resolved_at timestamptz);
create table public.students (id uuid primary key default uuid_generate_v4(), student_no text unique not null, full_name text not null, programme_id uuid references programmes(id));
create table public.theses (id uuid primary key default uuid_generate_v4(), student_id uuid not null references students(id) on delete cascade, supervisor_id uuid references faculty(id), title text not null, status text not null default 'Proposal', deadline date, updated_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.programmes enable row level security; alter table public.faculty enable row level security; alter table public.courses enable row level security; alter table public.course_offerings enable row level security; alter table public.allocations enable row level security; alter table public.conflicts enable row level security; alter table public.students enable row level security; alter table public.theses enable row level security;
create policy "authenticated read" on public.profiles for select to authenticated using (true); create policy "authenticated read" on public.programmes for select to authenticated using (true); create policy "authenticated read" on public.faculty for select to authenticated using (true); create policy "authenticated read" on public.courses for select to authenticated using (true); create policy "authenticated read" on public.course_offerings for select to authenticated using (true); create policy "authenticated read" on public.allocations for select to authenticated using (true); create policy "authenticated read" on public.conflicts for select to authenticated using (true); create policy "authenticated read" on public.students for select to authenticated using (true); create policy "authenticated read" on public.theses for select to authenticated using (true);
create policy "admin write" on public.allocations for all to authenticated using ((select role from profiles where id = auth.uid()) in ('admin','hod','coordinator')) with check ((select role from profiles where id = auth.uid()) in ('admin','hod','coordinator'));
create policy "admin update conflicts" on public.conflicts for update to authenticated using ((select role from profiles where id = auth.uid()) in ('admin','hod','coordinator'));
create or replace function public.allocate_course(p_offering_id uuid, p_faculty_id uuid) returns allocations language plpgsql security definer set search_path = public as $$ declare v_credits integer; begin select c.credits into v_credits from course_offerings o join courses c on c.id=o.course_id where o.id=p_offering_id; if v_credits is null then raise exception 'Course offering not found'; end if; insert into allocations(course_offering_id,faculty_id,assigned_credits,status) values(p_offering_id,p_faculty_id,v_credits,'allocated') on conflict(course_offering_id) do update set faculty_id=excluded.faculty_id,assigned_credits=excluded.assigned_credits,status='allocated'; return (select a from allocations a where a.course_offering_id=p_offering_id); end $$;
create or replace function public.dashboard_summary() returns json language sql security definer set search_path = public as $$ select json_build_object('courses', (select count(*) from course_offerings), 'allocated', (select count(*) from allocations where status='allocated'), 'conflicts', (select count(*) from conflicts where not resolved), 'faculty', (select count(*) from faculty)); $$;
