import {useEffect,useRef,useState} from "react";
import {MockActivityFeed} from "./mockFeed.js";

const FILTERS=["all","comment","like","follow","upload","mention"];
const LABELS={all:"All activity",comment:"Comments",like:"Likes",follow:"Follows",upload:"Uploads",mention:"Mentions"};
const GLYPHS={comment:"C",like:"L",follow:"+",upload:"U",mention:"@"};
const INITIAL={name:"Maya Chen",role:"Product Designer",bio:"I turn complex product ideas into clear, thoughtful experiences. Currently shaping collaboration tools at Northstar.",location:"San Francisco, CA",website:"mayachen.design",available:true};
function ago(ts){const s=Math.floor((Date.now()-ts)/1000);if(s<5)return"Just now";if(s<60)return`${s}s ago`;const m=Math.floor(s/60);if(m<60)return`${m}m ago`;const h=Math.floor(m/60);return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`}
const Avatar=({small})=><div className={`avatar ${small?"small":""}`}>MC</div>;
function Item({e}){return <article className="feed-item"><div className={`event-icon ${e.type}`}>{GLYPHS[e.type]}</div><div className="feed-copy"><p><strong>{e.actor}</strong> {e.verb} <strong>{e.target}</strong></p><time>{ago(e.ts)}</time></div><button className="row-arrow" aria-label="Open activity">›</button></article>}
function Shell({view,setView,children}){const nav=<><button className={view==="activity"?"active":""} onClick={()=>setView("activity")}><b>⌁</b><span>Activity</span></button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}><b>○</b><span>Profile</span></button></>;return <div className="shell"><aside><button className="brand" onClick={()=>setView("activity")}><i>⌁</i>ActivityLogs</button><nav>{nav}</nav><div className="side-user"><Avatar small/><div><strong>Maya Chen</strong><span>maya@northstar.co</span></div><button aria-label="Settings">•••</button></div></aside><header className="mobile-head"><span className="brand"><i>⌁</i>ActivityLogs</span><Avatar small/></header><main>{children}</main><nav className="mobile-nav">{nav}</nav></div>}
const Heading=({profile,editing,setEditing,save,cancel})=><header className="heading"><div><span>{profile?"PERSONAL SPACE":"WORKSPACE"}</span><h1>{profile?"Profile":"Activity"}</h1><p>{profile?"Manage how you show up to your team.":"Keep up with everything happening across your projects."}</p></div>{profile&&(editing?<div className="edit-actions"><button className="secondary" onClick={cancel}>Cancel</button><button className="primary" onClick={save}>✓ Save changes</button></div>:<button className="secondary" onClick={()=>setEditing(true)}>✎ Edit profile</button>)}</header>;
function Activity({data}){const list=data.filter==="all"?data.events:data.events.filter(e=>e.type===data.filter);return <div className="page"><Heading/><section className="panel"><div className="toolbar"><div className="filters">{FILTERS.map(id=><button key={id} className={data.filter===id?"active":""} onClick={()=>data.setFilter(id)}>{LABELS[id]}</button>)}</div><div className="status"><i className={data.status}/>{data.status==="online"?"Live":data.status==="offline"?"Reconnecting...":"Connecting..."}</div></div>{data.pending.length>0&&<button className="new-banner" onClick={data.flush}>{data.pending.length} new updates <b>View now</b></button>}<div className="feed-scroll" ref={data.scrollRef} onScroll={()=>data.atTop.current=data.scrollRef.current.scrollTop<40}>{data.events.length===0&&[1,2,3,4].map(n=><div className="skeleton" key={n}/>)}{list.map(e=><Item e={e} key={e.id}/>)}{list.length===0&&data.events.length>0&&<div className="empty"><strong>No activity here yet</strong><span>New updates will appear as they happen.</span></div>}{data.events.length>0&&<button className="load-more" onClick={data.loadMore} disabled={data.loading}>{data.loading?"Loading...":"Load older activity"}</button>}</div></section></div>}
function Profile({events}){const [profile,setProfile]=useState(()=>{try{return{...INITIAL,...JSON.parse(localStorage.getItem("pulse-profile"))}}catch{return INITIAL}}),[draft,setDraft]=useState(profile),[editing,setEditing]=useState(false);const field=k=>({value:draft[k],onChange:e=>setDraft({...draft,[k]:e.target.value})});const store=x=>{setProfile(x);setDraft(x);localStorage.setItem("pulse-profile",JSON.stringify(x))};return <div className="page profile-page"><Heading profile editing={editing} setEditing={setEditing} cancel={()=>{setDraft(profile);setEditing(false)}} save={()=>{store(draft);setEditing(false)}}/><section className="profile-card"><div className="cover"/><div className="identity-row"><Avatar/><div className="identity">{editing?<><input className="name-input" {...field("name")}/><input {...field("role")}/></>:<><h2>{profile.name}</h2><p>{profile.role}</p></>}</div><button className={`availability ${profile.available?"on":""}`} onClick={()=>store({...profile,available:!profile.available})}><i/>{profile.available?"Available":"Focus mode"}</button></div><div className="profile-body"><div className="about"><h3>About</h3>{editing?<textarea rows="4" maxLength="220" {...field("bio")}/>:<p>{profile.bio}</p>}<div className="details"><label>⌖ {editing?<input {...field("location")}/>:profile.location}</label><label>↗ {editing?<input {...field("website")}/>:<a href={`https://${profile.website}`}>{profile.website}</a>}</label><label>□ Joined March 2024</label></div></div><div className="stats"><div><strong>24</strong><span>Projects</span></div><div><strong>1.8k</strong><span>Contributions</span></div><div><strong>38</strong><span>Teammates</span></div></div></div></section><div className="profile-grid"><section className="block recent"><h2>Recent activity</h2><p>Your latest updates across ActivityLogs.</p>{events.slice(0,4).map(e=><Item e={{...e,actor:"You"}} key={e.id}/>)}</section><section className="block account"><h2>Account</h2><button><b>⚙</b><span><strong>Preferences</strong><small>Notifications and appearance</small></span><i>›</i></button><button><b>○</b><span><strong>Account details</strong><small>Email and password</small></span><i>›</i></button></section></div></div>}
export default function App(){const[view,setView]=useState(()=>location.hash==="#profile"?"profile":"activity"),[status,setStatus]=useState("connecting"),[events,setEvents]=useState([]),[pending,setPending]=useState([]),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(false),[page,setPage]=useState(1);const feedRef=useRef(),scrollRef=useRef(),atTop=useRef(true);useEffect(()=>{location.hash=view},[view]);useEffect(()=>{const f=new MockActivityFeed();feedRef.current=f;const s=e=>setStatus(e.detail.status),n=e=>atTop.current?setEvents(a=>[e.detail,...a]):setPending(a=>[e.detail,...a]);f.addEventListener("status",s);f.addEventListener("event",n);f.fetchHistoryPage(0).then(setEvents);return()=>f.close()},[]);const flush=()=>{setEvents(a=>[...pending,...a]);setPending([])};const loadMore=async()=>{setLoading(true);const n=page+1,o=await feedRef.current.fetchHistoryPage(n);setEvents(a=>[...a,...o]);setPage(n);setLoading(false)};const data={status,events,pending,flush,filter,setFilter,loading,loadMore,scrollRef,atTop};return <Shell {...{view,setView}}>{view==="activity"?<Activity data={data}/>:<Profile events={events}/>}</Shell>}
