begin;
create table if not exists public.payments (
 id bigint generated by default as identity primary key,
 receipt_no text not null unique,
 party_type text not null check(party_type in('customer','supplier')),
 customer_id bigint references public.customers(id),
 supplier_id bigint references public.suppliers(id),
 payment_date date not null default current_date,
 amount numeric(18,2) not null check(amount>0),
 payment_method text not null check(payment_method in('cash','bank')),
 reference text, notes text,
 status text not null default 'posted' check(status in('posted','reversed')),
 created_by uuid references auth.users(id), created_at timestamptz not null default now(),
 check((party_type='customer' and customer_id is not null and supplier_id is null) or (party_type='supplier' and supplier_id is not null and customer_id is null))
);
create index if not exists payments_customer_idx on public.payments(customer_id,payment_date desc);
create index if not exists payments_supplier_idx on public.payments(supplier_id,payment_date desc);

create or replace function public.post_party_payment(p_party_type text,p_party_id bigint,p_amount numeric,p_payment_method text,p_payment_date date,p_reference text,p_notes text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;v_cash bigint;v_party_account bigint;v_balance numeric;v_no text;
begin
 if p_amount<=0 then raise exception 'Amount must be positive';end if;
 select id into v_cash from public.accounts where lower(account_type)=lower(p_payment_method) and status=true order by id limit 1;
 if p_party_type='customer' then
  select coalesce(current_balance,0) into v_balance from public.customers where id=p_party_id for update;
  select id into v_party_account from public.accounts where lower(account_type) in('accounts_receivable','receivable') and status=true order by id limit 1;
 elsif p_party_type='supplier' then
  select coalesce(current_balance,0) into v_balance from public.suppliers where id=p_party_id for update;
  select id into v_party_account from public.accounts where lower(account_type) in('accounts_payable','payable') and status=true order by id limit 1;
 else raise exception 'Invalid party type';end if;
 if v_cash is null or v_party_account is null then raise exception 'Payment accounts are not configured';end if;
 if p_amount>v_balance then raise exception 'Payment exceeds outstanding balance %',v_balance;end if;
 v_no:='PAY-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
 insert into public.payments(receipt_no,party_type,customer_id,supplier_id,payment_date,amount,payment_method,reference,notes,created_by)
 values(v_no,p_party_type,case when p_party_type='customer' then p_party_id end,case when p_party_type='supplier' then p_party_id end,p_payment_date,p_amount,p_payment_method,p_reference,p_notes,auth.uid()) returning id into v_id;
 if p_party_type='customer' then
  update public.customers set current_balance=greatest(0,coalesce(current_balance,0)-p_amount) where id=p_party_id;
  insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_cash,p_payment_date,v_no,p_amount,0,'PAYMENT',v_id),(v_party_account,p_payment_date,v_no,0,p_amount,'PAYMENT',v_id);
 else
  update public.suppliers set current_balance=greatest(0,coalesce(current_balance,0)-p_amount) where id=p_party_id;
  insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_party_account,p_payment_date,v_no,p_amount,0,'PAYMENT',v_id),(v_cash,p_payment_date,v_no,0,p_amount,'PAYMENT',v_id);
 end if;
 return v_id;
end;$$;
grant execute on function public.post_party_payment(text,bigint,numeric,text,date,text,text) to authenticated;
alter table public.payments enable row level security;
create policy "authenticated_read_payments" on public.payments for select to authenticated using(true);
commit;
