begin;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  is_system boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  module text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  primary key(role_id,permission_id)
);
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role_id bigint references public.roles(id),
  status boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  action text not null,
  module text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists activity_logs_user_date_idx on public.activity_logs(user_id,created_at desc);
create index if not exists activity_logs_module_date_idx on public.activity_logs(module,created_at desc);

insert into public.roles(name,slug,description,is_system) values
('Admin','admin','Full system access',true),('Sub Admin','sub_admin','Administrative access excluding critical security settings',true),
('Manager','manager','Operational and reporting access',true),('Cashier','cashier','POS and customer access',true)
on conflict(slug) do nothing;

insert into public.permissions(name,code,module)
select initcap(replace(module,'_',' '))||' Access',module||'.view',module from unnest(array[
'dashboard','customers','suppliers','products','purchases','stock','pos','sales','accounts','expenses','payments','reports','users','roles','settings'
]) module on conflict(code) do nothing;
insert into public.permissions(name,code,module) values
('Manage Users','users.manage','users'),('Manage Roles','roles.manage','roles'),('Post Journal','accounts.journal','accounts'),('Adjust Stock','stock.adjust','stock')
on conflict(code) do nothing;

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p where r.slug='admin' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.slug='sub_admin' and p.module not in('roles') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.slug='manager' and p.module in('dashboard','customers','suppliers','products','purchases','stock','sales','expenses','payments','reports') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.slug='cashier' and p.code in('dashboard.view','customers.view','pos.view','sales.view') on conflict do nothing;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,full_name,role_id) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),(select id from public.roles where slug='cashier'));return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.has_permission(p_code text) returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.profiles pr join public.role_permissions rp on rp.role_id=pr.role_id join public.permissions p on p.id=rp.permission_id where pr.id=auth.uid() and pr.status=true and p.code=p_code);$$;
create or replace function public.get_my_access() returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('profile',to_jsonb(pr),'role',to_jsonb(r),'permissions',coalesce(jsonb_agg(p.code) filter(where p.code is not null),'[]'::jsonb))
from public.profiles pr left join public.roles r on r.id=pr.role_id left join public.role_permissions rp on rp.role_id=r.id left join public.permissions p on p.id=rp.permission_id where pr.id=auth.uid() group by pr.id,r.id;$$;
create or replace function public.assign_user_role(p_user_id uuid,p_role_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin if not public.has_permission('users.manage') then raise exception 'Forbidden';end if;update public.profiles set role_id=p_role_id where id=p_user_id;insert into public.activity_logs(user_id,action,module,entity_type,entity_id,metadata) values(auth.uid(),'role_assigned','users','profile',p_user_id::text,jsonb_build_object('role_id',p_role_id));end;$$;

grant execute on function public.has_permission(text) to authenticated;
grant execute on function public.get_my_access() to authenticated;
grant execute on function public.assign_user_role(uuid,bigint) to authenticated;
alter table public.roles enable row level security;alter table public.permissions enable row level security;alter table public.role_permissions enable row level security;alter table public.profiles enable row level security;alter table public.activity_logs enable row level security;
create policy "authenticated_read_roles" on public.roles for select to authenticated using(true);
create policy "authenticated_read_permissions" on public.permissions for select to authenticated using(true);
create policy "authenticated_read_role_permissions" on public.role_permissions for select to authenticated using(true);
create policy "profiles_read_self_or_admin" on public.profiles for select to authenticated using(id=auth.uid() or public.has_permission('users.manage'));
create policy "logs_read_admin" on public.activity_logs for select to authenticated using(public.has_permission('users.manage'));
commit;
