begin;

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  expense_no text not null unique,
  category_id bigint not null references public.expense_categories(id),
  expense_date date not null default current_date,
  amount numeric(18,2) not null check(amount > 0),
  payment_method text not null check(payment_method in ('cash','bank')),
  description text not null,
  receipt_url text,
  status text not null default 'posted' check(status in ('posted','reversed')),
  reversed_at timestamptz,
  reversal_reason text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists expenses_date_idx on public.expenses(expense_date desc);
create index if not exists expenses_category_idx on public.expenses(category_id,expense_date desc);

create or replace function public.post_expense(p_category_id bigint,p_expense_date date,p_amount numeric,p_payment_method text,p_description text,p_receipt_url text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint; v_expense_account bigint; v_payment_account bigint; v_no text;
begin
  if p_amount<=0 then raise exception 'Expense amount must be positive'; end if;
  select id into v_expense_account from public.accounts where lower(account_type) in('expense','operating_expense') and status=true order by id limit 1;
  select id into v_payment_account from public.accounts where lower(account_type)=lower(p_payment_method) and status=true order by id limit 1;
  if v_expense_account is null or v_payment_account is null then raise exception 'Expense or payment account is not configured'; end if;
  v_no:='EXP-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
  insert into public.expenses(expense_no,category_id,expense_date,amount,payment_method,description,receipt_url,created_by)
  values(v_no,p_category_id,p_expense_date,p_amount,p_payment_method,p_description,p_receipt_url,auth.uid()) returning id into v_id;
  insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values
    (v_expense_account,p_expense_date,v_no||' '||p_description,p_amount,0,'EXPENSE',v_id),
    (v_payment_account,p_expense_date,v_no||' '||p_description,0,p_amount,'EXPENSE',v_id);
  return v_id;
end; $$;

create or replace function public.reverse_expense(p_expense_id bigint,p_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare v_expense public.expenses; v_entry record;
begin
  select * into v_expense from public.expenses where id=p_expense_id for update;
  if v_expense.id is null or v_expense.status<>'posted' then raise exception 'Expense cannot be reversed'; end if;
  if nullif(trim(p_reason),'') is null then raise exception 'Reversal reason is required'; end if;
  for v_entry in select * from public.ledger_entries where reference_type='EXPENSE' and reference_id=p_expense_id loop
    insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id)
    values(v_entry.account_id,current_date,'Reversal: '||v_expense.expense_no,v_entry.credit,v_entry.debit,'EXPENSE_REVERSAL',p_expense_id);
  end loop;
  update public.expenses set status='reversed',reversed_at=now(),reversal_reason=p_reason where id=p_expense_id;
end; $$;

grant execute on function public.post_expense(bigint,date,numeric,text,text,text) to authenticated;
grant execute on function public.reverse_expense(bigint,text) to authenticated;
alter table public.expense_categories enable row level security;
alter table public.expenses enable row level security;
create policy "authenticated_manage_expense_categories" on public.expense_categories for all to authenticated using(true) with check(true);
create policy "authenticated_read_expenses" on public.expenses for select to authenticated using(true);

insert into storage.buckets(id,name,public) values('expense-receipts','expense-receipts',false) on conflict(id) do nothing;
create policy "users_upload_expense_receipts" on storage.objects for insert to authenticated with check(bucket_id='expense-receipts' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "users_read_expense_receipts" on storage.objects for select to authenticated using(bucket_id='expense-receipts');

commit;
