begin;

create table if not exists public.saved_filters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  module text not null,
  filter_config jsonb not null default '{}'::jsonb,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module, name)
);

create index if not exists saved_filters_user_module_idx
  on public.saved_filters(user_id, module, updated_at desc);
create index if not exists customers_search_idx
  on public.customers using gin (
    to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(phone, '') || ' ' || coalesce(email, ''))
  );
create index if not exists suppliers_search_idx
  on public.suppliers using gin (
    to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(phone, '') || ' ' || coalesce(email, ''))
  );
create index if not exists products_search_idx
  on public.products using gin (
    to_tsvector('simple', coalesce(product_name, '') || ' ' || coalesce(sku, '') || ' ' || coalesce(barcode, ''))
  );
create index if not exists invoices_number_search_idx
  on public.invoices(invoice_no);

create or replace function public.touch_saved_filter()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists saved_filters_touch_updated_at on public.saved_filters;
create trigger saved_filters_touch_updated_at
before update on public.saved_filters
for each row execute function public.touch_saved_filter();

create or replace function public.global_search(
  p_query text,
  p_types text[] default null,
  p_from date default null,
  p_to date default null,
  p_limit integer default 50
)
returns table (
  entity_type text,
  entity_id bigint,
  title text,
  subtitle text,
  status text,
  amount numeric,
  occurred_at timestamptz,
  action_url text,
  rank real
)
language sql
stable
security definer
set search_path = public
as $$
  with search_term as (
    select websearch_to_tsquery('simple', nullif(trim(p_query), '')) query
  ),
  results as (
    select
      'customer'::text entity_type,
      c.id entity_id,
      c.name title,
      concat_ws(' • ', nullif(c.phone, ''), nullif(c.email, '')) subtitle,
      case when c.status then 'active' else 'inactive' end status,
      coalesce(c.current_balance, 0)::numeric amount,
      c.created_at occurred_at,
      '/customers/' || c.id || '/edit' action_url,
      ts_rank(
        to_tsvector('simple', coalesce(c.name, '') || ' ' || coalesce(c.phone, '') || ' ' || coalesce(c.email, '')),
        s.query
      ) rank
    from public.customers c
    cross join search_term s
    where s.query is not null
      and to_tsvector('simple', coalesce(c.name, '') || ' ' || coalesce(c.phone, '') || ' ' || coalesce(c.email, '')) @@ s.query
      and (p_types is null or 'customer' = any(p_types))
      and (p_from is null or c.created_at::date >= p_from)
      and (p_to is null or c.created_at::date <= p_to)

    union all

    select
      'supplier',
      s.id,
      s.name,
      concat_ws(' • ', nullif(s.phone, ''), nullif(s.email, '')),
      case when s.status then 'active' else 'inactive' end,
      coalesce(s.current_balance, 0)::numeric,
      s.created_at,
      '/suppliers/' || s.id || '/edit',
      ts_rank(
        to_tsvector('simple', coalesce(s.name, '') || ' ' || coalesce(s.phone, '') || ' ' || coalesce(s.email, '')),
        q.query
      )
    from public.suppliers s
    cross join search_term q
    where q.query is not null
      and to_tsvector('simple', coalesce(s.name, '') || ' ' || coalesce(s.phone, '') || ' ' || coalesce(s.email, '')) @@ q.query
      and (p_types is null or 'supplier' = any(p_types))
      and (p_from is null or s.created_at::date >= p_from)
      and (p_to is null or s.created_at::date <= p_to)

    union all

    select
      'product',
      p.id,
      p.product_name,
      concat_ws(' • ', nullif(p.sku, ''), nullif(p.barcode, '')),
      case when p.status then 'active' else 'inactive' end,
      coalesce(p.sale_price, 0)::numeric,
      p.created_at,
      '/products/' || p.id,
      ts_rank(
        to_tsvector('simple', coalesce(p.product_name, '') || ' ' || coalesce(p.sku, '') || ' ' || coalesce(p.barcode, '')),
        s.query
      )
    from public.products p
    cross join search_term s
    where s.query is not null
      and to_tsvector('simple', coalesce(p.product_name, '') || ' ' || coalesce(p.sku, '') || ' ' || coalesce(p.barcode, '')) @@ s.query
      and (p_types is null or 'product' = any(p_types))
      and (p_from is null or p.created_at::date >= p_from)
      and (p_to is null or p.created_at::date <= p_to)

    union all

    select
      'sale',
      i.id,
      i.invoice_no,
      concat_ws(' • ', c.name, i.payment_method),
      i.status,
      coalesce(i.grand_total, 0)::numeric,
      i.invoice_date::timestamptz,
      '/sales/' || i.id,
      greatest(
        similarity(lower(i.invoice_no), lower(trim(p_query))),
        similarity(lower(coalesce(c.name, '')), lower(trim(p_query)))
      )::real
    from public.invoices i
    left join public.customers c on c.id = i.customer_id
    where nullif(trim(p_query), '') is not null
      and (
        i.invoice_no ilike '%' || trim(p_query) || '%'
        or c.name ilike '%' || trim(p_query) || '%'
      )
      and (p_types is null or 'sale' = any(p_types))
      and (p_from is null or i.invoice_date >= p_from)
      and (p_to is null or i.invoice_date <= p_to)
  )
  select *
  from results
  order by rank desc, occurred_at desc
  limit least(greatest(p_limit, 1), 200);
$$;

create or replace function public.save_user_filter(
  p_name text,
  p_module text,
  p_filter_config jsonb,
  p_is_default boolean default false
)
returns public.saved_filters
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.saved_filters;
begin
  if nullif(trim(p_name), '') is null then
    raise exception 'Filter name is required';
  end if;
  if jsonb_typeof(p_filter_config) <> 'object' then
    raise exception 'Filter configuration must be an object';
  end if;

  if p_is_default then
    update public.saved_filters
    set is_default = false
    where user_id = auth.uid() and module = p_module;
  end if;

  insert into public.saved_filters(user_id, name, module, filter_config, is_default)
  values (auth.uid(), trim(p_name), p_module, p_filter_config, p_is_default)
  on conflict (user_id, module, name)
  do update set
    filter_config = excluded.filter_config,
    is_default = excluded.is_default
  returning * into result;

  return result;
end;
$$;

alter table public.saved_filters enable row level security;

drop policy if exists "users_manage_own_saved_filters" on public.saved_filters;
create policy "users_manage_own_saved_filters"
on public.saved_filters for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, delete on public.saved_filters to authenticated;
grant execute on function public.global_search(text, text[], date, date, integer) to authenticated;
grant execute on function public.save_user_filter(text, text, jsonb, boolean) to authenticated;

commit;
