begin;

alter table public.accounts
  add column if not exists account_code text,
  add column if not exists opening_balance numeric(18,2) not null default 0,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists accounts_code_uidx on public.accounts(account_code) where account_code is not null;

create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  journal_no text not null unique,
  transaction_date date not null default current_date,
  description text not null,
  reference text,
  status text not null default 'posted' check(status in ('draft','posted','reversed')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.journal_entry_items (
  id bigint generated by default as identity primary key,
  journal_entry_id bigint not null references public.journal_entries(id) on delete restrict,
  account_id bigint not null references public.accounts(id),
  debit numeric(18,2) not null default 0 check(debit >= 0),
  credit numeric(18,2) not null default 0 check(credit >= 0),
  check ((debit > 0 and credit = 0) or (credit > 0 and debit = 0))
);

create index if not exists journal_entries_date_idx on public.journal_entries(transaction_date desc);
create index if not exists journal_items_account_idx on public.journal_entry_items(account_id);
create index if not exists ledger_account_date_idx on public.ledger_entries(account_id, transaction_date);

create or replace function public.post_manual_journal(
  p_transaction_date date,
  p_description text,
  p_reference text,
  p_items jsonb
)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint; v_item jsonb; v_debit numeric:=0; v_credit numeric:=0; v_no text;
begin
  if jsonb_array_length(p_items)<2 then raise exception 'At least two journal lines are required'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_debit:=v_debit+coalesce((v_item->>'debit')::numeric,0);
    v_credit:=v_credit+coalesce((v_item->>'credit')::numeric,0);
    if coalesce((v_item->>'debit')::numeric,0)<0 or coalesce((v_item->>'credit')::numeric,0)<0 then raise exception 'Negative journal amounts are not allowed'; end if;
  end loop;
  if v_debit<=0 or abs(v_debit-v_credit)>0.005 then raise exception 'Journal is not balanced. Debit %, Credit %',v_debit,v_credit; end if;
  v_no:='JV-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
  insert into public.journal_entries(journal_no,transaction_date,description,reference,created_by)
  values(v_no,p_transaction_date,p_description,p_reference,auth.uid()) returning id into v_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    insert into public.journal_entry_items(journal_entry_id,account_id,debit,credit)
    values(v_id,(v_item->>'account_id')::bigint,coalesce((v_item->>'debit')::numeric,0),coalesce((v_item->>'credit')::numeric,0));
    insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id)
    values((v_item->>'account_id')::bigint,p_transaction_date,p_description,coalesce((v_item->>'debit')::numeric,0),coalesce((v_item->>'credit')::numeric,0),'JOURNAL',v_id);
  end loop;
  return v_id;
end; $$;

create or replace function public.set_account_opening_balance(p_account_id bigint,p_amount numeric,p_as_of date)
returns void language plpgsql security definer set search_path=public as $$
declare v_account public.accounts; v_equity bigint; v_debit numeric:=0; v_credit numeric:=0;
begin
  select * into v_account from public.accounts where id=p_account_id for update;
  if v_account.id is null then raise exception 'Account not found'; end if;
  if exists(select 1 from public.ledger_entries where reference_type='OPENING_BALANCE' and reference_id=p_account_id) then raise exception 'Opening balance already posted'; end if;
  select id into v_equity from public.accounts where lower(account_type) in('opening_equity','equity') and status=true order by id limit 1;
  if v_equity is null then raise exception 'Opening equity account is not configured'; end if;
  if lower(v_account.account_type) in('asset','cash','bank','inventory','accounts_receivable','receivable','expense','cogs','cost_of_goods_sold') then v_debit:=abs(p_amount); else v_credit:=abs(p_amount); end if;
  insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values
    (p_account_id,p_as_of,'Opening balance',v_debit,v_credit,'OPENING_BALANCE',p_account_id),
    (v_equity,p_as_of,'Opening balance offset',v_credit,v_debit,'OPENING_BALANCE',p_account_id);
  update public.accounts set opening_balance=p_amount where id=p_account_id;
end; $$;

grant execute on function public.post_manual_journal(date,text,text,jsonb) to authenticated;
grant execute on function public.set_account_opening_balance(bigint,numeric,date) to authenticated;
alter table public.journal_entries enable row level security;
alter table public.journal_entry_items enable row level security;
create policy "authenticated_read_journals" on public.journal_entries for select to authenticated using(true);
create policy "authenticated_read_journal_items" on public.journal_entry_items for select to authenticated using(true);

commit;
