begin;

create table if not exists public.accounts (
 id bigint generated by default as identity primary key, account_code text unique, account_name text not null,
 account_type text not null, opening_balance numeric(18,2) not null default 0, status boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.customers (
 id bigint generated by default as identity primary key, customer_code text unique default ('CUS-'||substr(md5(random()::text),1,8)),
 name text not null, phone text, email text, address text, opening_balance numeric(18,2) not null default 0,
 current_balance numeric(18,2) not null default 0, credit_limit numeric(18,2) not null default 0,
 status boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.suppliers (
 id bigint generated by default as identity primary key, supplier_code text unique default ('SUP-'||substr(md5(random()::text),1,8)),
 name text not null, phone text, email text, address text, notes text, opening_balance numeric(18,2) not null default 0,
 current_balance numeric(18,2) not null default 0, credit_limit numeric(18,2) not null default 0,
 status boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.categories (id bigint generated by default as identity primary key,name text not null unique,description text,status boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.brands (id bigint generated by default as identity primary key,name text not null unique,description text,status boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.units (id bigint generated by default as identity primary key,name text not null unique,short_name text not null,status boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.products (
 id bigint generated by default as identity primary key, name text not null, product_name text, sku text not null unique, barcode text unique,
 category_id bigint not null references public.categories(id), brand_id bigint references public.brands(id), unit_id bigint not null references public.units(id),
 cost_price numeric(18,2) not null default 0, purchase_price numeric(18,2), sale_price numeric(18,2) not null default 0,
 wholesale_price numeric(18,2) not null default 0, minimum_stock numeric(18,4) not null default 0,
 image_url text, status boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create or replace function public.sync_product_compatibility() returns trigger language plpgsql as $$begin new.product_name:=coalesce(nullif(new.product_name,''),new.name);new.name:=coalesce(nullif(new.name,''),new.product_name);new.purchase_price:=coalesce(new.purchase_price,new.cost_price,0);new.cost_price:=coalesce(new.cost_price,new.purchase_price,0);new.updated_at:=now();return new;end;$$;
drop trigger if exists products_sync_compatibility on public.products;create trigger products_sync_compatibility before insert or update on public.products for each row execute function public.sync_product_compatibility();

create table if not exists public.stock (id bigint generated by default as identity primary key,product_id bigint not null references public.products(id),quantity numeric(18,4) not null default 0 check(quantity>=0),created_at timestamptz not null default now());
create table if not exists public.invoices (
 id bigint generated by default as identity primary key, invoice_no text not null unique, customer_id bigint references public.customers(id),
 invoice_date date not null default current_date, subtotal numeric(18,2) not null default 0, discount numeric(18,2) not null default 0,
 tax numeric(18,2) not null default 0, grand_total numeric(18,2) not null default 0, paid_amount numeric(18,2) not null default 0,
 due_amount numeric(18,2) not null default 0, payment_method text not null default 'cash', created_at timestamptz not null default now()
);
create table if not exists public.invoice_items (
 id bigint generated by default as identity primary key, invoice_id bigint not null references public.invoices(id) on delete restrict,
 product_id bigint not null references public.products(id), quantity numeric(18,4) not null check(quantity>0),
 sale_price numeric(18,2) not null, discount numeric(18,2) not null default 0, total numeric(18,2) not null
);
create table if not exists public.ledger_entries (
 id bigint generated by default as identity primary key,account_id bigint not null references public.accounts(id),transaction_date date not null default current_date,
 description text not null,debit numeric(18,2) not null default 0,credit numeric(18,2) not null default 0,
 reference_type text,reference_id bigint,reference_no text,created_at timestamptz not null default now(),check(debit>=0 and credit>=0)
);
-- Created here because search/report migrations reference these tables before the full purchase migration extends them.
create table if not exists public.purchases (
 id bigint generated by default as identity primary key,purchase_no text unique,supplier_id bigint not null references public.suppliers(id),
 purchase_date date not null default current_date,subtotal numeric(18,2) not null default 0,discount numeric(18,2) not null default 0,
 tax numeric(18,2) not null default 0,grand_total numeric(18,2) not null default 0,paid_amount numeric(18,2) not null default 0,
 due_amount numeric(18,2) not null default 0,payment_method text not null default 'credit',status text not null default 'completed',created_at timestamptz not null default now()
);
create table if not exists public.purchase_items (id bigint generated by default as identity primary key,purchase_id bigint not null references public.purchases(id),product_id bigint not null references public.products(id),quantity numeric(18,4) not null check(quantity>0),purchase_price numeric(18,2) not null default 0,total numeric(18,2) not null default 0);

create index if not exists customers_name_idx on public.customers(name);create index if not exists suppliers_name_idx on public.suppliers(name);create index if not exists products_name_idx on public.products(name);create index if not exists products_barcode_idx on public.products(barcode);create index if not exists invoices_date_idx on public.invoices(invoice_date desc);create index if not exists ledger_date_idx on public.ledger_entries(transaction_date desc);

insert into public.accounts(account_code,account_name,account_type,status) values
('1000','Cash on Hand','cash',true),('1010','Bank Account','bank',true),('1100','Accounts Receivable','accounts_receivable',true),
('1200','Inventory','inventory',true),('2000','Accounts Payable','accounts_payable',true),('3000','Opening Balance Equity','equity',true),
('4000','Sales Revenue','revenue',true),('4100','Other Income','revenue',true),('5000','Cost of Goods Sold','cogs',true),('6000','Operating Expenses','expense',true)
on conflict(account_code) do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp']),
('expense-receipts','expense-receipts',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do nothing;

alter table public.accounts enable row level security;alter table public.customers enable row level security;alter table public.suppliers enable row level security;alter table public.categories enable row level security;alter table public.brands enable row level security;alter table public.units enable row level security;alter table public.products enable row level security;alter table public.stock enable row level security;alter table public.invoices enable row level security;alter table public.invoice_items enable row level security;alter table public.ledger_entries enable row level security;alter table public.purchases enable row level security;alter table public.purchase_items enable row level security;
do $$declare t text;begin foreach t in array array['accounts','customers','suppliers','categories','brands','units','products'] loop execute format('drop policy if exists authenticated_manage_%I on public.%I',t,t);execute format('create policy authenticated_manage_%I on public.%I for all to authenticated using (true) with check (true)',t,t);end loop;foreach t in array array['stock','invoices','invoice_items','ledger_entries','purchases','purchase_items'] loop execute format('drop policy if exists authenticated_read_%I on public.%I',t,t);execute format('create policy authenticated_read_%I on public.%I for select to authenticated using (true)',t,t);end loop;end$$;
drop policy if exists authenticated_product_images_read on storage.objects;create policy authenticated_product_images_read on storage.objects for select to authenticated using(bucket_id='product-images');drop policy if exists authenticated_product_images_write on storage.objects;create policy authenticated_product_images_write on storage.objects for insert to authenticated with check(bucket_id='product-images');drop policy if exists authenticated_expense_receipts on storage.objects;create policy authenticated_expense_receipts on storage.objects for all to authenticated using(bucket_id='expense-receipts' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='expense-receipts' and (storage.foldername(name))[1]=auth.uid()::text);

grant usage on schema public to authenticated;grant select,insert,update on public.accounts,public.customers,public.suppliers,public.categories,public.brands,public.units,public.products to authenticated;grant select on public.stock,public.invoices,public.invoice_items,public.ledger_entries,public.purchases,public.purchase_items to authenticated;grant usage,select on all sequences in schema public to authenticated;
commit;

