begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  type text not null check (type in ('info', 'success', 'warning', 'error')),
  category text not null check (category in ('system', 'stock', 'payment', 'security')),
  title text not null,
  message text not null,
  action_url text,
  entity_type text,
  entity_id text,
  unique_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.notification_reads (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

create unique index if not exists notifications_unique_key_uidx
  on public.notifications(unique_key)
  where unique_key is not null;
create index if not exists notifications_user_date_idx
  on public.notifications(user_id, created_at desc);
create index if not exists notifications_category_date_idx
  on public.notifications(category, created_at desc);
create index if not exists notifications_expiry_idx
  on public.notifications(expires_at)
  where expires_at is not null;
create index if not exists notification_reads_user_idx
  on public.notification_reads(user_id, read_at desc);

create or replace function public.get_my_notifications(
  p_limit integer default 30,
  p_unread_only boolean default false
)
returns table (
  id bigint,
  type text,
  category text,
  title text,
  message text,
  action_url text,
  entity_type text,
  entity_id text,
  metadata jsonb,
  created_at timestamptz,
  read_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    n.id,
    n.type,
    n.category,
    n.title,
    n.message,
    n.action_url,
    n.entity_type,
    n.entity_id,
    n.metadata,
    n.created_at,
    nr.read_at
  from public.notifications n
  left join public.notification_reads nr
    on nr.notification_id = n.id
   and nr.user_id = auth.uid()
  where (n.user_id is null or n.user_id = auth.uid())
    and (n.expires_at is null or n.expires_at > now())
    and (not p_unread_only or nr.read_at is null)
  order by n.created_at desc
  limit least(greatest(p_limit, 1), 100);
$$;

create or replace function public.mark_notification_read(p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.notifications n
    where n.id = p_notification_id
      and (n.user_id is null or n.user_id = auth.uid())
  ) then
    raise exception 'Notification not found';
  end if;

  insert into public.notification_reads(notification_id, user_id)
  values (p_notification_id, auth.uid())
  on conflict (notification_id, user_id)
  do update set read_at = now();
end;
$$;

create or replace function public.mark_all_notifications_read()
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notification_reads(notification_id, user_id)
  select n.id, auth.uid()
  from public.notifications n
  where (n.user_id is null or n.user_id = auth.uid())
    and (n.expires_at is null or n.expires_at > now())
  on conflict (notification_id, user_id)
  do update set read_at = now();
$$;

create or replace function public.refresh_system_alerts()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (
    type, category, title, message, action_url,
    entity_type, entity_id, unique_key, metadata
  )
  select
    case when s.quantity <= 0 then 'error' else 'warning' end,
    'stock',
    case when s.quantity <= 0 then 'Out of stock' else 'Low stock' end,
    p.product_name || ' has ' || trim(to_char(s.quantity, 'FM999999990.####')) || ' units remaining.',
    '/stock',
    'product',
    p.id::text,
    'stock:' || p.id || ':' || s.warehouse_id,
    jsonb_build_object(
      'product_id', p.id,
      'warehouse_id', s.warehouse_id,
      'quantity', s.quantity,
      'minimum_stock', coalesce(p.minimum_stock, 0)
    )
  from public.stock s
  join public.products p on p.id = s.product_id
  where p.status = true
    and s.quantity <= coalesce(p.minimum_stock, 0)
  on conflict (unique_key) where unique_key is not null
  do update set
    type = excluded.type,
    title = excluded.title,
    message = excluded.message,
    metadata = excluded.metadata,
    created_at = now(),
    expires_at = null;

  update public.notifications n
  set expires_at = now()
  where n.category = 'stock'
    and n.unique_key is not null
    and not exists (
      select 1
      from public.stock s
      join public.products p on p.id = s.product_id
      where 'stock:' || p.id || ':' || s.warehouse_id = n.unique_key
        and p.status = true
        and s.quantity <= coalesce(p.minimum_stock, 0)
    );

  insert into public.notifications (
    type, category, title, message, action_url,
    entity_type, entity_id, unique_key, metadata
  )
  select
    'warning',
    'payment',
    'Customer payment outstanding',
    c.name || ' has an outstanding balance of ' || to_char(c.current_balance, 'FM999999990.00') || '.',
    '/payments',
    'customer',
    c.id::text,
    'customer-due:' || c.id,
    jsonb_build_object('customer_id', c.id, 'balance', c.current_balance)
  from public.customers c
  where c.status = true and coalesce(c.current_balance, 0) > 0
  on conflict (unique_key) where unique_key is not null
  do update set
    message = excluded.message,
    metadata = excluded.metadata,
    created_at = now(),
    expires_at = null;

  insert into public.notifications (
    type, category, title, message, action_url,
    entity_type, entity_id, unique_key, metadata
  )
  select
    'warning',
    'payment',
    'Supplier payment outstanding',
    s.name || ' has an outstanding balance of ' || to_char(s.current_balance, 'FM999999990.00') || '.',
    '/payments',
    'supplier',
    s.id::text,
    'supplier-due:' || s.id,
    jsonb_build_object('supplier_id', s.id, 'balance', s.current_balance)
  from public.suppliers s
  where s.status = true and coalesce(s.current_balance, 0) > 0
  on conflict (unique_key) where unique_key is not null
  do update set
    message = excluded.message,
    metadata = excluded.metadata,
    created_at = now(),
    expires_at = null;

  update public.notifications n
  set expires_at = now()
  where n.category = 'payment'
    and (
      (n.entity_type = 'customer' and not exists (
        select 1 from public.customers c
        where c.id::text = n.entity_id and c.status = true and coalesce(c.current_balance, 0) > 0
      ))
      or
      (n.entity_type = 'supplier' and not exists (
        select 1 from public.suppliers s
        where s.id::text = n.entity_id and s.status = true and coalesce(s.current_balance, 0) > 0
      ))
    );
end;
$$;

create or replace function public.notify_stock_threshold()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_system_alerts();
  return new;
end;
$$;

drop trigger if exists stock_threshold_notification on public.stock;
create trigger stock_threshold_notification
after insert or update of quantity on public.stock
for each statement execute function public.notify_stock_threshold();

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;

drop policy if exists "users_read_available_notifications" on public.notifications;
create policy "users_read_available_notifications"
on public.notifications for select
to authenticated
using (
  (user_id is null or user_id = auth.uid())
  and (expires_at is null or expires_at > now())
);

drop policy if exists "users_read_own_notification_reads" on public.notification_reads;
create policy "users_read_own_notification_reads"
on public.notification_reads for select
to authenticated
using (user_id = auth.uid());

grant execute on function public.get_my_notifications(integer, boolean) to authenticated;
grant execute on function public.mark_notification_read(bigint) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
grant execute on function public.refresh_system_alerts() to authenticated;

commit;
