begin;

alter table public.invoices
  add column if not exists status text not null default 'completed'
  check (status in ('completed', 'partially_returned', 'returned', 'cancelled')),
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancellation_reason text;

create index if not exists invoices_status_date_idx on public.invoices(status, invoice_date desc);
create index if not exists invoices_customer_date_idx on public.invoices(customer_id, invoice_date desc);

create table if not exists public.sales_returns (
  id bigint generated by default as identity primary key,
  return_no text not null unique,
  invoice_id bigint not null references public.invoices(id),
  customer_id bigint references public.customers(id),
  warehouse_id bigint not null references public.warehouses(id),
  total_amount numeric(18,2) not null check (total_amount > 0),
  refund_method text not null check (refund_method in ('cash', 'card', 'credit')),
  reason text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.sales_return_items (
  id bigint generated by default as identity primary key,
  sales_return_id bigint not null references public.sales_returns(id) on delete cascade,
  invoice_item_id bigint not null references public.invoice_items(id),
  product_id bigint not null references public.products(id),
  quantity numeric(18,4) not null check (quantity > 0),
  sale_price numeric(18,2) not null,
  total numeric(18,2) not null
);

create index if not exists sales_returns_invoice_idx on public.sales_returns(invoice_id, created_at desc);
create index if not exists sales_return_items_product_idx on public.sales_return_items(product_id);

create or replace function public.cancel_sale(p_invoice_id bigint, p_warehouse_id bigint, p_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare v_invoice public.invoices; v_item record; v_stock public.stock; v_entry record;
begin
  select * into v_invoice from public.invoices where id = p_invoice_id for update;
  if v_invoice.id is null then raise exception 'Invoice not found'; end if;
  if v_invoice.status <> 'completed' then raise exception 'Only completed invoices can be cancelled'; end if;
  if nullif(trim(p_reason),'') is null then raise exception 'Cancellation reason is required'; end if;

  for v_item in select * from public.invoice_items where invoice_id = p_invoice_id loop
    insert into public.stock(product_id, warehouse_id, quantity) values(v_item.product_id,p_warehouse_id,v_item.quantity)
    on conflict(product_id,warehouse_id) do update set quantity=public.stock.quantity+excluded.quantity returning * into v_stock;
    insert into public.stock_movements(product_id,warehouse_id,movement_type,quantity,balance_after,reference_type,reference_id,notes,created_by)
    values(v_item.product_id,p_warehouse_id,'sale_return',v_item.quantity,v_stock.quantity,'sale_cancel',p_invoice_id,p_reason,auth.uid());
  end loop;

  for v_entry in select * from public.ledger_entries where reference_type='SALE' and reference_id=p_invoice_id loop
    insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id)
    values(v_entry.account_id,current_date,'Cancellation: '||v_invoice.invoice_no,v_entry.credit,v_entry.debit,'SALE_CANCEL',p_invoice_id);
  end loop;
  if v_invoice.customer_id is not null and v_invoice.due_amount > 0 then
    update public.customers set current_balance=greatest(0,coalesce(current_balance,0)-v_invoice.due_amount) where id=v_invoice.customer_id;
  end if;
  update public.invoices set status='cancelled',cancelled_at=now(),cancellation_reason=p_reason where id=p_invoice_id;
end; $$;

create or replace function public.return_sale(p_invoice_id bigint,p_warehouse_id bigint,p_items jsonb,p_refund_method text,p_reason text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_invoice public.invoices; v_item jsonb; v_original public.invoice_items; v_returned numeric; v_return_id bigint; v_total numeric:=0; v_total_cogs numeric:=0; v_unit_cost numeric; v_line numeric; v_stock public.stock; v_refund_account bigint; v_sales bigint; v_inventory bigint; v_cogs bigint;
begin
  select * into v_invoice from public.invoices where id=p_invoice_id for update;
  if v_invoice.id is null or v_invoice.status in ('cancelled','returned') then raise exception 'Invoice cannot be returned'; end if;
  if jsonb_array_length(p_items)=0 then raise exception 'Return items are required'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_original from public.invoice_items where id=(v_item->>'invoice_item_id')::bigint and invoice_id=p_invoice_id;
    select coalesce(sum(sri.quantity),0) into v_returned from public.sales_return_items sri join public.sales_returns sr on sr.id=sri.sales_return_id where sr.invoice_id=p_invoice_id and sri.invoice_item_id=v_original.id;
    if v_original.id is null or (v_item->>'quantity')::numeric<=0 or v_returned+(v_item->>'quantity')::numeric>v_original.quantity then raise exception 'Invalid return quantity'; end if;
    v_total:=v_total+((v_item->>'quantity')::numeric*v_original.sale_price);
  end loop;
  insert into public.sales_returns(return_no,invoice_id,customer_id,warehouse_id,total_amount,refund_method,reason,created_by)
  values('RET-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS'),p_invoice_id,v_invoice.customer_id,p_warehouse_id,v_total,p_refund_method,p_reason,auth.uid()) returning id into v_return_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_original from public.invoice_items where id=(v_item->>'invoice_item_id')::bigint;
    v_line:=(v_item->>'quantity')::numeric*v_original.sale_price;
    select coalesce(purchase_price,0) into v_unit_cost from public.products where id=v_original.product_id;
    v_total_cogs:=v_total_cogs+((v_item->>'quantity')::numeric*v_unit_cost);
    insert into public.sales_return_items(sales_return_id,invoice_item_id,product_id,quantity,sale_price,total) values(v_return_id,v_original.id,v_original.product_id,(v_item->>'quantity')::numeric,v_original.sale_price,v_line);
    insert into public.stock(product_id,warehouse_id,quantity) values(v_original.product_id,p_warehouse_id,(v_item->>'quantity')::numeric)
    on conflict(product_id,warehouse_id) do update set quantity=public.stock.quantity+excluded.quantity returning * into v_stock;
    insert into public.stock_movements(product_id,warehouse_id,movement_type,quantity,balance_after,reference_type,reference_id,notes,created_by) values(v_original.product_id,p_warehouse_id,'sale_return',(v_item->>'quantity')::numeric,v_stock.quantity,'sales_return',v_return_id,p_reason,auth.uid());
  end loop;
  select id into v_sales from public.accounts where lower(account_type) in('sales','revenue') and status=true order by id limit 1;
  select id into v_refund_account from public.accounts where lower(account_type)=case when p_refund_method='card' then 'bank' when p_refund_method='credit' then 'accounts_receivable' else 'cash' end and status=true order by id limit 1;
  select id into v_inventory from public.accounts where lower(account_type) in('inventory','stock') and status=true order by id limit 1;
  select id into v_cogs from public.accounts where lower(account_type) in('cost_of_goods_sold','cogs') and status=true order by id limit 1;
  if v_sales is null or v_refund_account is null or v_inventory is null or v_cogs is null then raise exception 'Return ledger accounts are not configured'; end if;
  insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values
    (v_sales,current_date,'Sales return',v_total,0,'SALE_RETURN',v_return_id),
    (v_refund_account,current_date,'Sales refund',0,v_total,'SALE_RETURN',v_return_id),
    (v_inventory,current_date,'Returned inventory',v_total_cogs,0,'SALE_RETURN',v_return_id),
    (v_cogs,current_date,'COGS reversal',0,v_total_cogs,'SALE_RETURN',v_return_id);
  if p_refund_method='credit' and v_invoice.customer_id is not null then
    update public.customers set current_balance=greatest(0,coalesce(current_balance,0)-v_total) where id=v_invoice.customer_id;
  end if;
  update public.invoices set status=case when (select coalesce(sum(sri.quantity),0) from public.sales_return_items sri join public.sales_returns sr on sr.id=sri.sales_return_id where sr.invoice_id=p_invoice_id) >= (select sum(quantity) from public.invoice_items where invoice_id=p_invoice_id) then 'returned' else 'partially_returned' end where id=p_invoice_id;
  return v_return_id;
end; $$;

grant execute on function public.cancel_sale(bigint,bigint,text) to authenticated;
grant execute on function public.return_sale(bigint,bigint,jsonb,text,text) to authenticated;
alter table public.sales_returns enable row level security;
alter table public.sales_return_items enable row level security;
create policy "authenticated_read_sales_returns" on public.sales_returns for select to authenticated using(true);
create policy "authenticated_read_sales_return_items" on public.sales_return_items for select to authenticated using(true);

commit;
