begin;

create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  address text,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.warehouses (name, code)
values ('Main Warehouse', 'MAIN')
on conflict (code) do nothing;

alter table public.stock
  add column if not exists warehouse_id bigint references public.warehouses(id),
  add column if not exists updated_at timestamptz not null default now();

update public.stock
set warehouse_id = (select id from public.warehouses where code = 'MAIN')
where warehouse_id is null;

alter table public.stock alter column warehouse_id set not null;

create unique index if not exists stock_product_warehouse_uidx
  on public.stock(product_id, warehouse_id);
create index if not exists stock_quantity_idx on public.stock(quantity);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  warehouse_id bigint not null references public.warehouses(id),
  movement_type text not null check (
    movement_type in ('opening', 'purchase', 'sale', 'sale_return', 'purchase_return', 'adjustment', 'damage', 'transfer_in', 'transfer_out')
  ),
  quantity numeric(18,4) not null check (quantity <> 0),
  balance_after numeric(18,4) not null check (balance_after >= 0),
  reference_type text,
  reference_id bigint,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists stock_movements_product_idx
  on public.stock_movements(product_id, created_at desc);
create index if not exists stock_movements_warehouse_idx
  on public.stock_movements(warehouse_id, created_at desc);
create index if not exists stock_movements_reference_idx
  on public.stock_movements(reference_type, reference_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists warehouses_set_updated_at on public.warehouses;
create trigger warehouses_set_updated_at
before update on public.warehouses
for each row execute function public.set_updated_at();

drop trigger if exists stock_set_updated_at on public.stock;
create trigger stock_set_updated_at
before update on public.stock
for each row execute function public.set_updated_at();

create or replace function public.adjust_stock(
  p_product_id bigint,
  p_warehouse_id bigint,
  p_quantity numeric,
  p_movement_type text,
  p_notes text default null
)
returns public.stock
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock public.stock;
  v_new_quantity numeric;
begin
  if p_quantity = 0 then
    raise exception 'Quantity cannot be zero';
  end if;

  if p_movement_type not in ('adjustment', 'damage') then
    raise exception 'Unsupported manual movement type';
  end if;

  if p_movement_type = 'damage' and p_quantity > 0 then
    raise exception 'Damage quantity must reduce stock';
  end if;

  insert into public.stock (product_id, warehouse_id, quantity)
  values (p_product_id, p_warehouse_id, 0)
  on conflict (product_id, warehouse_id) do nothing;

  select * into v_stock
  from public.stock
  where product_id = p_product_id and warehouse_id = p_warehouse_id
  for update;

  v_new_quantity := v_stock.quantity + p_quantity;
  if v_new_quantity < 0 then
    raise exception 'Insufficient stock. Available: %', v_stock.quantity;
  end if;

  update public.stock
  set quantity = v_new_quantity
  where id = v_stock.id
  returning * into v_stock;

  insert into public.stock_movements (
    product_id, warehouse_id, movement_type, quantity, balance_after, notes, created_by
  )
  values (
    p_product_id, p_warehouse_id, p_movement_type, p_quantity, v_new_quantity, p_notes, auth.uid()
  );

  return v_stock;
end;
$$;

revoke all on function public.adjust_stock(bigint, bigint, numeric, text, text) from public;
grant execute on function public.adjust_stock(bigint, bigint, numeric, text, text) to authenticated;

create or replace function public.set_opening_stock(
  p_product_id bigint,
  p_quantity numeric
)
returns public.stock
language plpgsql
security definer
set search_path = public
as $$
declare
  v_warehouse_id bigint;
  v_stock public.stock;
begin
  if p_quantity < 0 then
    raise exception 'Opening stock cannot be negative';
  end if;

  select id into v_warehouse_id from public.warehouses where code = 'MAIN';

  insert into public.stock (product_id, warehouse_id, quantity)
  values (p_product_id, v_warehouse_id, p_quantity)
  on conflict (product_id, warehouse_id) do update
  set quantity = excluded.quantity
  where public.stock.quantity = 0
  returning * into v_stock;

  if v_stock.id is null then
    raise exception 'Opening stock can only be set when current stock is zero';
  end if;

  if p_quantity > 0 then
    insert into public.stock_movements (
      product_id, warehouse_id, movement_type, quantity, balance_after, reference_type, notes, created_by
    )
    values (
      p_product_id, v_warehouse_id, 'opening', p_quantity, p_quantity, 'opening_stock', 'Opening stock', auth.uid()
    );
  end if;

  return v_stock;
end;
$$;

revoke all on function public.set_opening_stock(bigint, numeric) from public;
grant execute on function public.set_opening_stock(bigint, numeric) to authenticated;

alter table public.warehouses enable row level security;
alter table public.stock enable row level security;
alter table public.stock_movements enable row level security;

drop policy if exists "authenticated_read_warehouses" on public.warehouses;
create policy "authenticated_read_warehouses" on public.warehouses
for select to authenticated using (true);

drop policy if exists "authenticated_read_stock" on public.stock;
create policy "authenticated_read_stock" on public.stock
for select to authenticated using (true);

drop policy if exists "authenticated_read_stock_movements" on public.stock_movements;
create policy "authenticated_read_stock_movements" on public.stock_movements
for select to authenticated using (true);

commit;
