begin;

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  purchase_no text not null unique,
  supplier_id bigint not null references public.suppliers(id),
  warehouse_id bigint references public.warehouses(id),
  purchase_date date not null default current_date,
  subtotal numeric(18,2) not null default 0,
  discount numeric(18,2) not null default 0,
  tax numeric(18,2) not null default 0,
  grand_total numeric(18,2) not null default 0,
  paid_amount numeric(18,2) not null default 0,
  due_amount numeric(18,2) not null default 0,
  payment_method text not null default 'credit',
  status text not null default 'completed',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.purchases add column if not exists purchase_no text, add column if not exists warehouse_id bigint references public.warehouses(id), add column if not exists subtotal numeric(18,2) default 0, add column if not exists discount numeric(18,2) default 0, add column if not exists tax numeric(18,2) default 0, add column if not exists grand_total numeric(18,2) default 0, add column if not exists paid_amount numeric(18,2) default 0, add column if not exists due_amount numeric(18,2) default 0, add column if not exists payment_method text default 'credit', add column if not exists status text default 'completed', add column if not exists created_at timestamptz default now();
create unique index if not exists purchases_no_uidx on public.purchases(purchase_no);

create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete restrict,
  product_id bigint not null references public.products(id),
  quantity numeric(18,4) not null check(quantity>0),
  purchase_price numeric(18,2) not null check(purchase_price>=0),
  total numeric(18,2) not null default 0
);
alter table public.purchase_items add column if not exists purchase_price numeric(18,2) default 0, add column if not exists total numeric(18,2) default 0;

create table if not exists public.purchase_returns (
  id bigint generated by default as identity primary key,
  return_no text not null unique,
  purchase_id bigint not null references public.purchases(id),
  supplier_id bigint not null references public.suppliers(id),
  warehouse_id bigint not null references public.warehouses(id),
  return_date date not null default current_date,
  total_amount numeric(18,2) not null default 0,
  reason text not null,
  status text not null default 'completed',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.purchase_return_items (
  id bigint generated by default as identity primary key,
  purchase_return_id bigint not null references public.purchase_returns(id) on delete restrict,
  purchase_item_id bigint not null references public.purchase_items(id),
  product_id bigint not null references public.products(id),
  quantity numeric(18,4) not null check(quantity>0),
  purchase_price numeric(18,2) not null,
  total numeric(18,2) not null
);

create or replace function public.post_purchase(p_supplier_id bigint,p_warehouse_id bigint,p_items jsonb,p_discount numeric,p_tax numeric,p_paid_amount numeric,p_payment_method text,p_purchase_date date)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;v_no text;v_item jsonb;v_subtotal numeric:=0;v_total numeric;v_due numeric;v_stock public.stock;v_inventory bigint;v_ap bigint;v_cash bigint;
begin
 if jsonb_array_length(p_items)=0 then raise exception 'At least one item is required';end if;
 if p_discount<0 or p_tax<0 or p_paid_amount<0 then raise exception 'Amounts cannot be negative';end if;
 for v_item in select * from jsonb_array_elements(p_items) loop
  if (v_item->>'quantity')::numeric<=0 or (v_item->>'purchase_price')::numeric<0 then raise exception 'Invalid item quantity or price';end if;
  v_subtotal:=v_subtotal+(v_item->>'quantity')::numeric*(v_item->>'purchase_price')::numeric;
 end loop;
 v_total:=v_subtotal-p_discount+p_tax;if v_total<0 then raise exception 'Grand total cannot be negative';end if;
 if p_paid_amount>v_total then raise exception 'Paid amount exceeds purchase total';end if;v_due:=v_total-p_paid_amount;
 select id into v_inventory from public.accounts where lower(account_type) in('inventory','stock') and status=true order by id limit 1;
 select id into v_ap from public.accounts where lower(account_type) in('accounts_payable','payable') and status=true order by id limit 1;
 if p_paid_amount>0 then select id into v_cash from public.accounts where lower(account_type)=case when lower(p_payment_method)='bank' then 'bank' else 'cash' end and status=true order by id limit 1;end if;
 if v_inventory is null or (v_due>0 and v_ap is null) or (p_paid_amount>0 and v_cash is null) then raise exception 'Required purchase ledger accounts are not configured';end if;
 v_no:='PUR-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');
 insert into public.purchases(purchase_no,supplier_id,warehouse_id,purchase_date,subtotal,discount,tax,grand_total,paid_amount,due_amount,payment_method,status,created_by) values(v_no,p_supplier_id,p_warehouse_id,coalesce(p_purchase_date,current_date),v_subtotal,p_discount,p_tax,v_total,p_paid_amount,v_due,p_payment_method,'completed',auth.uid()) returning id into v_id;
 for v_item in select * from jsonb_array_elements(p_items) loop
  insert into public.purchase_items(purchase_id,product_id,quantity,purchase_price,total) values(v_id,(v_item->>'product_id')::bigint,(v_item->>'quantity')::numeric,(v_item->>'purchase_price')::numeric,(v_item->>'quantity')::numeric*(v_item->>'purchase_price')::numeric);
  insert into public.stock(product_id,warehouse_id,quantity) values((v_item->>'product_id')::bigint,p_warehouse_id,0) on conflict(product_id,warehouse_id) do nothing;
  update public.stock set quantity=quantity+(v_item->>'quantity')::numeric where product_id=(v_item->>'product_id')::bigint and warehouse_id=p_warehouse_id returning * into v_stock;
  update public.products set purchase_price=(v_item->>'purchase_price')::numeric where id=(v_item->>'product_id')::bigint;
  insert into public.stock_movements(product_id,warehouse_id,movement_type,quantity,balance_after,reference_type,reference_id,notes,created_by) values((v_item->>'product_id')::bigint,p_warehouse_id,'purchase',(v_item->>'quantity')::numeric,v_stock.quantity,'purchase',v_id,v_no,auth.uid());
 end loop;
 insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_inventory,coalesce(p_purchase_date,current_date),v_no,v_total,0,'PURCHASE',v_id);
 if v_due>0 then insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_ap,coalesce(p_purchase_date,current_date),v_no,0,v_due,'PURCHASE',v_id);update public.suppliers set current_balance=coalesce(current_balance,0)+v_due where id=p_supplier_id;end if;
 if p_paid_amount>0 then insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_cash,coalesce(p_purchase_date,current_date),v_no,0,p_paid_amount,'PURCHASE',v_id);end if;
 return v_id;
end;$$;

create or replace function public.post_purchase_return(p_purchase_id bigint,p_warehouse_id bigint,p_items jsonb,p_reason text,p_return_date date)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_purchase public.purchases;v_item jsonb;v_pi public.purchase_items;v_stock public.stock;v_qty numeric;v_prev numeric;v_total numeric:=0;v_id bigint;v_no text;v_inventory bigint;v_ap bigint;
begin
 if coalesce(trim(p_reason),'')='' then raise exception 'Return reason is required';end if;select * into v_purchase from public.purchases where id=p_purchase_id and status<>'cancelled' for update;if v_purchase.id is null then raise exception 'Purchase not found';end if;
 for v_item in select * from jsonb_array_elements(p_items) loop
  v_qty:=(v_item->>'quantity')::numeric;if v_qty<=0 then raise exception 'Return quantity must be positive';end if;select * into v_pi from public.purchase_items where id=(v_item->>'purchase_item_id')::bigint and purchase_id=p_purchase_id;if v_pi.id is null then raise exception 'Invalid purchase item';end if;
  select coalesce(sum(quantity),0) into v_prev from public.purchase_return_items where purchase_item_id=v_pi.id;if v_qty+v_prev>v_pi.quantity then raise exception 'Return exceeds purchased quantity';end if;
  select * into v_stock from public.stock where product_id=v_pi.product_id and warehouse_id=p_warehouse_id for update;if v_stock.id is null or v_stock.quantity<v_qty then raise exception 'Insufficient stock to return';end if;v_total:=v_total+v_qty*v_pi.purchase_price;
 end loop;
 select id into v_inventory from public.accounts where lower(account_type) in('inventory','stock') and status=true order by id limit 1;select id into v_ap from public.accounts where lower(account_type) in('accounts_payable','payable') and status=true order by id limit 1;if v_inventory is null or v_ap is null then raise exception 'Purchase return accounts are not configured';end if;
 v_no:='PRET-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');insert into public.purchase_returns(return_no,purchase_id,supplier_id,warehouse_id,return_date,total_amount,reason,created_by) values(v_no,p_purchase_id,v_purchase.supplier_id,p_warehouse_id,coalesce(p_return_date,current_date),v_total,p_reason,auth.uid()) returning id into v_id;
 for v_item in select * from jsonb_array_elements(p_items) loop select * into v_pi from public.purchase_items where id=(v_item->>'purchase_item_id')::bigint;v_qty:=(v_item->>'quantity')::numeric;insert into public.purchase_return_items(purchase_return_id,purchase_item_id,product_id,quantity,purchase_price,total) values(v_id,v_pi.id,v_pi.product_id,v_qty,v_pi.purchase_price,v_qty*v_pi.purchase_price);update public.stock set quantity=quantity-v_qty where product_id=v_pi.product_id and warehouse_id=p_warehouse_id returning * into v_stock;insert into public.stock_movements(product_id,warehouse_id,movement_type,quantity,balance_after,reference_type,reference_id,notes,created_by) values(v_pi.product_id,p_warehouse_id,'purchase_return',-v_qty,v_stock.quantity,'purchase_return',v_id,v_no,auth.uid());end loop;
 insert into public.ledger_entries(account_id,transaction_date,description,debit,credit,reference_type,reference_id) values(v_ap,coalesce(p_return_date,current_date),v_no,v_total,0,'PURCHASE_RETURN',v_id),(v_inventory,coalesce(p_return_date,current_date),v_no,0,v_total,'PURCHASE_RETURN',v_id);update public.suppliers set current_balance=greatest(0,coalesce(current_balance,0)-v_total) where id=v_purchase.supplier_id;return v_id;
end;$$;

grant execute on function public.post_purchase(bigint,bigint,jsonb,numeric,numeric,numeric,text,date) to authenticated;
grant execute on function public.post_purchase_return(bigint,bigint,jsonb,text,date) to authenticated;
alter table public.purchases enable row level security;alter table public.purchase_items enable row level security;alter table public.purchase_returns enable row level security;alter table public.purchase_return_items enable row level security;
drop policy if exists authenticated_read_purchases on public.purchases;create policy authenticated_read_purchases on public.purchases for select to authenticated using(true);
drop policy if exists authenticated_read_purchase_items on public.purchase_items;create policy authenticated_read_purchase_items on public.purchase_items for select to authenticated using(true);
drop policy if exists authenticated_read_purchase_returns on public.purchase_returns;create policy authenticated_read_purchase_returns on public.purchase_returns for select to authenticated using(true);
drop policy if exists authenticated_read_purchase_return_items on public.purchase_return_items;create policy authenticated_read_purchase_return_items on public.purchase_return_items for select to authenticated using(true);
commit;
