import { useMemo, useState } from "react";

const initial = {email:"",name:"",address:"",apt:"",city:"",country:"United States",zip:"",save:false,payment:"card",card:"",cardName:"",expiry:"",cvc:""};

const Icon=({name,size=20})=>{const p={
 lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
 mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>,
 user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
 pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
 card:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h3"/></>,
 truck:<><path d="M10 17h4V5H2v12h3m9-8h4l4 4v4h-3"/><circle cx="7.5" cy="17.5" r="2.5"/><circle cx="16.5" cy="17.5" r="2.5"/></>,
 shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
 check:<path d="m5 12 4 4L19 6"/>,arrow:<path d="m9 18 6-6-6-6"/>
};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>};

function validate(f){const e={};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))e.email="Enter a valid email address";if(f.name.trim().length<2)e.name="Enter your full name";if(f.address.trim().length<4)e.address="Enter a valid street address";if(!f.city.trim())e.city="City is required";if(!/^[A-Za-z0-9 -]{3,10}$/.test(f.zip.trim()))e.zip="Enter a valid postal code";if(f.payment==="card"){if(!/^\d{16}$/.test(f.card.replace(/\s/g,"")))e.card="Enter all 16 card digits";if(!f.cardName.trim())e.cardName="Name on card is required";const m=f.expiry.match(/^(0[1-9]|1[0-2])\/(\d{2})$/);if(!m||new Date(2000+Number(m[2]),Number(m[1]))<=new Date())e.expiry="Enter a valid future date";if(!/^\d{3,4}$/.test(f.cvc))e.cvc="Enter 3–4 digits"}return e}

function Field({label,name,value,error,touched,onChange,onBlur,icon,...props}){return <div className="field"><label htmlFor={name}>{label}</label><div className={"input-wrap "+(touched&&error?"invalid":"")}>{icon&&<span className="input-icon"><Icon name={icon} size={17}/></span>}<input id={name} name={name} value={value} onChange={onChange} onBlur={onBlur} aria-invalid={!!(touched&&error)} aria-describedby={error?name+"-error":undefined} {...props}/></div>{touched&&error&&<p className="error" id={name+"-error"} role="alert">{error}</p>}</div>}

export default function App(){
 const [form,setForm]=useState(initial),[touched,setTouched]=useState({}),[done,setDone]=useState(false);const errors=useMemo(()=>validate(form),[form]);const subtotal=187.99,tax=15.04,total=subtotal+tax;
 const set=(name,value)=>setForm(f=>({...f,[name]:value}));const fp=name=>({name,value:form[name],error:errors[name],touched:touched[name],onChange:e=>set(name,e.target.value),onBlur:()=>setTouched(t=>({...t,[name]:true}))});
 const card=v=>v.replace(/\D/g,"").slice(0,16).replace(/(.{4})/g,"$1 ").trim();const exp=v=>{const d=v.replace(/\D/g,"").slice(0,4);return d.length>2?d.slice(0,2)+"/"+d.slice(2):d};
 const submit=e=>{e.preventDefault();if(Object.keys(errors).length){setTouched(Object.fromEntries(Object.keys(initial).map(k=>[k,true])));requestAnimationFrame(()=>document.querySelector("[aria-invalid='true']")?.focus());return}setDone(true);window.scrollTo({top:0,behavior:"smooth"})};
 if(done)return <main className="page"><section className="success-card"><div className="success-mark"><Icon name="check" size={34}/></div><p className="eyebrow">Order #CL-2048</p><h1>Thank you, {form.name.split(" ")[0]}!</h1><p>Your order is confirmed. We sent the receipt and delivery details to <strong>{form.email}</strong>.</p><div className="success-total"><span>Total paid</span><strong>$203.03</strong></div><button className="primary" onClick={()=>{setDone(false);setForm(initial);setTouched({})}}>Return to checkout</button></section></main>;
 return <main className="page"><header className="topbar"><a className="brand" href="#" aria-label="Receipt home"><span>R</span>RECEIPT</a><div className="secure"><Icon name="lock" size={15}/> Secure checkout</div></header><div className="checkout-grid"><section className="checkout">
  <div className="heading"><p className="eyebrow">Almost yours</p><h1>Complete your order</h1><p>Enter your details below. Your information is encrypted and secure.</p></div>
  <form onSubmit={submit} noValidate>
   <section className="form-section"><Title n="1" title="Contact information" note="We'll send your receipt and order updates here."/><Field label="Email address" type="email" autoComplete="email" placeholder="you@example.com" icon="mail" {...fp("email")}/></section>
   <section className="form-section"><Title n="2" title="Shipping address" note="Where should we deliver your order?"/><Field label="Full name" autoComplete="name" placeholder="Alex Morgan" icon="user" {...fp("name")}/><Field label="Street address" autoComplete="street-address" placeholder="123 Market Street" icon="pin" {...fp("address")}/><div className="optional-field"><label htmlFor="apt">Apartment, suite, etc. <span>Optional</span></label><input id="apt" value={form.apt} onChange={e=>set("apt",e.target.value)} placeholder="Apt 4B"/></div><div className="field-grid three"><Field label="City" placeholder="San Francisco" {...fp("city")}/><div className="field"><label htmlFor="country">Country</label><div className="input-wrap"><select id="country" value={form.country} onChange={e=>set("country",e.target.value)}><option>United States</option><option>Canada</option><option>United Kingdom</option><option>Pakistan</option></select></div></div><Field label="Postal code" inputMode="numeric" placeholder="94103" {...fp("zip")}/></div><label className="check-row"><input type="checkbox" checked={form.save} onChange={e=>set("save",e.target.checked)}/><span className="fake-check"><Icon name="check" size={14}/></span><span>Save this information for next time</span></label></section>
   <section className="form-section"><Title n="3" title="Payment" note="All transactions are secure and encrypted."/><div className="method-list" role="radiogroup" aria-label="Payment method">{[["card","Credit card","Visa, Mastercard, Amex","card"],["paypal","PayPal","Pay with your account","P"],["cod","Cash on delivery","Pay when it arrives","truck"]].map(([id,title,note,symbol])=><label className={"method "+(form.payment===id?"selected":"")} key={id}><input type="radio" name="payment" checked={form.payment===id} onChange={()=>set("payment",id)}/><span className="radio-dot"/><span className="method-copy"><strong>{title}</strong><small>{note}</small></span><span className={"method-icon "+(symbol==="P"?"paypal":"")}>{symbol==="P"?"P":<Icon name={symbol} size={21}/>}</span></label>)}</div>
   {form.payment==="card"?<div className="card-fields"><Field label="Card number" inputMode="numeric" autoComplete="cc-number" placeholder="1234 5678 9012 3456" icon="card" {...fp("card")} onChange={e=>set("card",card(e.target.value))}/><Field label="Name on card" autoComplete="cc-name" placeholder="Alex Morgan" {...fp("cardName")}/><div className="field-grid"><Field label="Expiration date" inputMode="numeric" placeholder="MM/YY" {...fp("expiry")} onChange={e=>set("expiry",exp(e.target.value))}/><Field label="Security code" inputMode="numeric" placeholder="CVC" {...fp("cvc")} onChange={e=>set("cvc",e.target.value.replace(/\D/g,"").slice(0,4))}/></div></div>:<div className="payment-note"><Icon name={form.payment==="cod"?"truck":"shield"}/><p><strong>{form.payment==="cod"?"Pay at your doorstep":"Continue securely with PayPal"}</strong><br/>{form.payment==="cod"?"Have the exact amount ready when your order arrives.":"After placing your order, you'll be redirected to PayPal."}</p></div>}</section>
   <button className="primary place-order" type="submit"><span>Place order</span><span>$203.03 <Icon name="arrow" size={17}/></span></button><p className="terms"><Icon name="lock" size={13}/> By placing your order, you agree to our Terms and Privacy Policy.</p>
  </form></section><Summary subtotal={subtotal} tax={tax} total={total}/></div></main>
}
const Title=({n,title,note})=><div className="section-title"><span>{n}</span><div><h2>{title}</h2><p>{note}</p></div></div>;
function Summary({subtotal,tax,total}){return <aside className="order-card"><div className="summary-head"><h2>Order summary</h2><span>2 items</span></div><Product type="bottle" name="Daily Hydration Set" detail="Ocean · 24 oz" price="128.00"/><Product type="pouch" name="Travel Essentials Kit" detail="Sand" price="59.99"/><div className="divider"/><div className="price-row"><span>Subtotal</span><b>${subtotal.toFixed(2)}</b></div><div className="price-row"><span>Shipping</span><b className="free">Free</b></div><div className="price-row"><span>Estimated tax</span><b>${tax.toFixed(2)}</b></div><div className="divider"/><div className="total-row"><span><b>Total</b><small>USD</small></span><strong>${total.toFixed(2)}</strong></div><div className="delivery"><Icon name="truck"/><div><strong>Free standard delivery</strong><span>Arrives Aug 22–25</span></div></div><div className="trust"><Icon name="shield" size={18}/><span><strong>30-day guarantee</strong><br/>Free, easy returns</span></div></aside>}
const Product=({type,name,detail,price})=><div className="product"><div className={"product-image "+type}><span>{type==="bottle"?"CLV":"+"}</span></div><div className="product-info"><strong>{name}</strong><span>{detail}</span><small>Qty 1</small></div><b>${price}</b></div>;

