import { useEffect, useMemo, useRef, useState } from "react";
import { useDebouncedValue, useQueryParamState } from "./hooks.js";
import { searchAll } from "./searchData.js";
const FILTERS = ["All", "Documents", "People", "Files"];
const paths = { search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, document: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/></>, person: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, file: <path d="M15 7 8.5 13.5a3 3 0 0 0 4.2 4.2l7.1-7.1a5 5 0 0 0-7.1-7.1L5 11.2a7 7 0 0 0 9.9 9.9l6.1-6.1"/>, sparkle: <><path d="m12 3-1.4 3.6L7 8l3.6 1.4L12 13l1.4-3.6L17 8l-3.6-1.4L12 3Z"/><path d="m5 15-.8 2.2L2 18l2.2.8L5 21l.8-2.2L8 18l-2.2-.8L5 15Z"/></>, arrow: <path d="M5 12h14M13 6l6 6-6 6"/>, x: <path d="m6 6 12 12M18 6 6 18"/> };
function Icon({name,size=18}) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>; }
const typeIcons = {Document:"document",Person:"person",File:"file"};
export default function App() {
 const [query,setQuery]=useQueryParamState("q",""); const debounced=useDebouncedValue(query,400); const [results,setResults]=useState([]); const [status,setStatus]=useState("idle"); const [calls,setCalls]=useState(0); const [filter,setFilter]=useState("All"); const latest=useRef(0); const input=useRef(null);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();input.current?.focus()}if(e.key==="Escape"&&document.activeElement===input.current)setQuery("")};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[setQuery]);
 useEffect(()=>{if(!debounced.trim()){latest.current++;setResults([]);setStatus("idle");return}const id=++latest.current;setStatus("searching");setCalls(c=>c+1);searchAll(debounced).then(data=>{if(id!==latest.current)return;setResults(data);setStatus("done")})},[debounced]);
 const visible=useMemo(()=>filter==="All"?results:results.filter(r=>r.type===filter.slice(0,-1)),[filter,results]); const typing=query!==debounced, working=typing||status==="searching";
 return <main className="app-shell"><nav className="topbar"><a className="brand" href="/"><span className="brand-mark"><Icon name="sparkle" size={17}/></span>Finder</a><div className="nav-actions"><span className="plan-badge">PRO</span><button className="avatar" aria-label="Open profile">AY</button></div></nav>
 <section className="hero"><div className="eyebrow"><span className="live-dot"/>Universal search</div><h1>Find anything, instantly.</h1><p>Search across your documents, teammates, and files from one beautifully simple place.</p><div className={`search-panel ${working?"is-working":""}`}><div className="search-input-wrap"><Icon name="search" size={22}/><input ref={input} type="search" aria-label="Search workspace" placeholder="Search your workspace..." value={query} onChange={e=>setQuery(e.target.value)} autoFocus/>{query?<button className="clear-button" onClick={()=>setQuery("")} aria-label="Clear search"><Icon name="x" size={16}/></button>:<kbd>⌘ K</kbd>}</div><div className="search-meta"><span>{typing?"Waiting for you to finish typing...":status==="searching"?"Searching your workspace...":status==="done"?`${results.length} matches found`:"Start typing to explore"}</span><span className="request-stat"><b>{calls}</b> optimized {calls===1?"request":"requests"}</span></div></div></section>
 <section className="results-area" aria-live="polite">{(status!=="idle"||typing)&&<div className="results-toolbar"><div className="filters">{FILTERS.map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><span>{visible.length} results</span></div>}{working&&<div className="result-list">{[1,2,3].map(n=><div className="result-card skeleton" key={n}><span/><div><i/><i/></div></div>)}</div>}{!working&&status==="done"&&!visible.length&&<div className="empty-state"><div className="empty-icon"><Icon name="search" size={28}/></div><h2>No matches found</h2><p>Try another keyword or choose a different category.</p></div>}{!working&&status==="done"&&visible.length>0&&<div className="result-list">{visible.map((r,i)=><button className="result-card" key={r.id} style={{"--delay":`${i*45}ms`}}><span className={`type-icon ${r.type.toLowerCase()}`}><Icon name={typeIcons[r.type]} size={20}/></span><span className="result-copy"><strong>{r.title}</strong><small>{r.excerpt}</small></span><span className="type-label">{r.type}</span><span className="result-arrow"><Icon name="arrow" size={18}/></span></button>)}</div>}</section><footer><span><Icon name="sparkle" size={13}/>Powered by smart debounce</span><span>Press <b>Esc</b> to clear</span></footer></main>;
}

