import {useCallback,useRef,useState} from "react";
const MAX=10*1024*1024,TYPES=["image/png","image/jpeg","image/webp","application/pdf"];
const Icon=({name,size=20})=>{const p={upload:<><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5"/><path d="M5 14v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4"/></>,file:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8"/></>,check:<path d="m5 12 4 4L19 6"/>,x:<path d="m6 6 12 12M18 6 6 18"/>,plus:<path d="M12 5v14M5 12h14"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>};
const format=b=>b<1048576?`${Math.max(1,Math.round(b/1024))} KB`:`${(b/1048576).toFixed(1)} MB`,validate=f=>!TYPES.includes(f.type)?"File type not supported":f.size>MAX?"File is larger than 10 MB":null;
function Row({item,remove}){return <article className={`file-card ${item.error?"has-error":""}`}><div className={`preview ${item.file.type==="application/pdf"?"pdf":""}`}>{item.preview?<img src={item.preview} alt=""/>:<Icon name="file" size={22}/>}</div><div className="file-info"><div className="file-heading"><strong title={item.file.name}>{item.file.name}</strong><button className="icon-button" onClick={()=>remove(item.id)} aria-label="Remove file"><Icon name="x" size={18}/></button></div><div className="file-detail"><span>{format(item.file.size)}</span>{item.error?<span className="failure">{item.error}</span>:item.progress===100?<span className="success"><Icon name="check" size={14}/> Complete</span>:<span>Uploading - {item.progress}%</span>}</div>{!item.error&&<div className="progress"><i style={{width:`${item.progress}%`}}/></div>}</div></article>}
export default function App(){const[files,setFiles]=useState([]),[drag,setDrag]=useState(false),[submitted,setSubmitted]=useState(false),input=useRef(),ids=useRef(0),timers=useRef(new Map());
const upload=useCallback(id=>{let p=0;const t=setInterval(()=>{p=Math.min(100,p+Math.ceil(Math.random()*12));setFiles(a=>a.map(x=>x.id===id?{...x,progress:p}:x));if(p===100){clearInterval(t);timers.current.delete(id)}},300);timers.current.set(id,t)},[]);
const add=useCallback(list=>{setSubmitted(false);const next=Array.from(list).map(file=>({id:++ids.current,file,error:validate(file),progress:0,preview:file.type.startsWith("image/")?URL.createObjectURL(file):null}));setFiles(a=>[...a,...next]);next.filter(x=>!x.error).forEach(x=>upload(x.id));if(input.current)input.current.value=""},[upload]);
const remove=id=>{const x=files.find(f=>f.id===id);if(x?.preview)URL.revokeObjectURL(x.preview);clearInterval(timers.current.get(id));setFiles(a=>a.filter(f=>f.id!==id))},clear=()=>{files.forEach(x=>{if(x.preview)URL.revokeObjectURL(x.preview);clearInterval(timers.current.get(x.id))});timers.current.clear();setFiles([])},done=files.filter(x=>x.progress===100).length,busy=files.some(x=>!x.error&&x.progress<100);
if(submitted)return <main className="page-shell"><section className="uploader-card success-screen"><div className="success-mark"><Icon name="check" size={34}/></div><small>Upload complete</small><h1>Your files are ready</h1><p>{done} {done===1?"file has":"files have"} been added to your media library.</p><button className="continue" onClick={()=>{clear();setSubmitted(false)}}>Upload more files</button></section></main>; return <main className="page-shell"><section className="uploader-card"><header><div><small>Media library</small><h1>Upload your files</h1><p>Add images or documents to your workspace.</p></div><b>Step 1 of 2</b></header><div className={`dropzone ${drag?"drag":""}`} role="button" tabIndex="0" onClick={()=>input.current?.click()} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add(e.dataTransfer.files)}}><div className="upload-icon"><Icon name="upload" size={28}/></div><h2>{drag?"Drop your files here":"Drag & drop files here"}</h2><p>or <em>browse files</em> from your computer</p><div className="rules">PNG, JPG, WEBP or PDF <i/> Max 10 MB each</div><input ref={input} type="file" accept=".png,.jpg,.jpeg,.webp,.pdf" multiple onChange={e=>add(e.target.files)}/></div>{files.length>0&&<section className="uploads"><div className="uploads-title"><span><strong>Uploads</strong> {files.length} files</span><button onClick={()=>input.current?.click()}><Icon name="plus" size={16}/> Add more</button></div><div className="file-list">{files.map(x=><Row key={x.id} item={x} remove={remove}/>)}</div></section>}<footer><span>{files.length?<><strong>{done} of {files.length}</strong> files ready</>:"No files selected yet"}</span><div>{files.length>0&&<button className="clear" onClick={clear}>Clear all</button>}<button className="continue" disabled={!done||busy} onClick={()=>setSubmitted(true)}>Finish upload &rarr;</button></div></footer></section><p className="privacy">Your files are private and securely encrypted.</p></main>}



