-- Run in your Supabase project's SQL Editor.
create table if not exists public.task_67_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  status text not null check (status in ('In progress', 'Complete', 'Planned'))
);
alter table public.task_67_items enable row level security;
drop policy if exists "Public can read task demo" on public.task_67_items;
create policy "Public can read task demo" on public.task_67_items for select to anon, authenticated using (true);
grant select on public.task_67_items to anon, authenticated;
insert into public.task_67_items (id, name, category, status)
select n, 'Task ' || n || ': Improve workspace experience',
  (array['Engineering','Design','Product','Marketing'])[1 + (n - 1) % 4],
  (array['In progress','Complete','Planned'])[1 + (n - 1) % 3]
from generate_series(1,1500) as n on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.task_67_items','id'), greatest((select max(id) from public.task_67_items),1));
