import { useMemo, useState } from "react";
const DAY=86400000;
const seed=[
 {id:1,type:"mention",title:"You were mentioned in a comment",desc:"Maya Chen mentioned you in Q4 Product Roadmap",avatar:"MC",color:"coral",time:Date.now()-480000,read:false,replies:[]},
 {id:2,type:"assignment",title:"New task assigned to you",desc:"Review onboarding flow has been assigned to you",avatar:"AM",color:"blue",time:Date.now()-2280000,read:false,replies:[]},
 {id:3,type:"system",title:"Workspace security update",desc:"Two-factor authentication is now available for your team",icon:"shield",color:"violet",time:Date.now()-10800000,read:false,replies:[]},
 {id:4,type:"comment",title:"New reply to your thread",desc:"Jordan replied: This direction looks great. Let's ship it.",avatar:"JL",color:"mint",time:Date.now()-DAY-7200000,read:true,replies:["Thanks, Jordan! I'll move it forward."]},
 {id:5,type:"success",title:"Project milestone completed",desc:"Your team completed Website refresh - Phase 1",icon:"check",color:"green",time:Date.now()-DAY-18000000,read:true,replies:[]},
 {id:6,type:"invite",title:"You joined Design Crew",desc:"Sofia invited you to the Design Crew workspace",avatar:"SK",color:"amber",time:Date.now()-DAY*4,read:true,replies:[]}
];
function Icon({name,size=20}){const p={bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,inbox:<><path d="M4 4h16v16H4z"/><path d="M4 14h4l2 3h4l2-3h4"/></>,check:<path d="m5 12 4 4L19 6"/>,double:<><path d="m2 12 4 4L16 6"/><path d="m10 16 4 4L24 8"/></>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,shield:<><path d="M12 22s8-3.5 8-10V5l-8-3-8 3v7c0 6.5 8 10 8 10"/><path d="m9 12 2 2 4-4"/></>,spark:<path d="m12 3 1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,plus:<><path d="M12 5v14M5 12h14"/></>,reply:<><path d="m9 17-5-5 5-5"/><path d="M20 18v-2a4 4 0 0 0-4-4H4"/></>,edit:<><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></>,trash:<><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>}
const ago=t=>{const m=Math.max(1,Math.floor((Date.now()-t)/60000)),h=Math.floor(m/60);return m<60?`${m}m`:h<24?`${h}h`:`${Math.floor(h/24)}d`};
function day(t){const n=new Date(),d=new Date(t),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate()),x=Math.round((a-b)/DAY);return x===0?"Today":x===1?"Yesterday":"Earlier"}
function Visual({item}){if(item.avatar)return <div className={`avatar ${item.color}`}>{item.avatar}<span className={`type-badge ${item.type}`}>{item.type==="mention"?"@":item.type==="assignment"?"✓":item.type==="comment"?"↩":"+"}</span></div>;return <div className={`event-icon ${item.color}`}><Icon name={item.icon} size={21}/></div>}
function Modal({mode,item,onClose,onSave}){const [title,setTitle]=useState(item?.title||""),[desc,setDesc]=useState(item?.desc||"");const reply=mode==="reply";return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={e=>{e.preventDefault();onSave({title,desc})}}><div className="modal-head"><div><span>{reply?"SEND A REPLY":mode==="edit"?"EDIT NOTIFICATION":"NEW NOTIFICATION"}</span><h2>{reply?item.title:mode==="edit"?"Update notification":"Create notification"}</h2></div><button type="button" onClick={onClose}><Icon name="close"/></button></div>{reply?<label>Message<textarea autoFocus required value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Write a thoughtful reply..."/></label>:<><label>Title<input autoFocus required maxLength="80" value={title} onChange={e=>setTitle(e.target.value)} placeholder="What happened?"/></label><label>Description<textarea required value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Add some helpful context..."/></label></>}<div className="modal-actions"><button type="button" className="cancel" onClick={onClose}>Cancel</button><button className="primary">{reply?"Send reply":mode==="edit"?"Save changes":"Create notification"}</button></div></form></div>}
export default function App(){
 const [items,setItems]=useState(seed),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[toast,setToast]=useState(""),[menu,setMenu]=useState(null),[dialog,setDialog]=useState(null);
 const unread=items.filter(x=>!x.read).length;const visible=useMemo(()=>items.filter(x=>(filter==="all"||!x.read)&&`${x.title} ${x.desc}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);const groups=useMemo(()=>visible.reduce((a,x)=>{(a[day(x.time)]||=[]).push(x);return a},{}),[visible]);
 const flash=text=>{setToast(text);setTimeout(()=>setToast(""),2200)},toggle=id=>setItems(a=>a.map(x=>x.id===id?{...x,read:!x.read}:x));
 const remove=id=>{setItems(a=>a.filter(x=>x.id!==id));setMenu(null);flash("Notification deleted")};
 const save=data=>{if(dialog.mode==="create"){setItems(a=>[{id:Date.now(),type:"mention",title:data.title,desc:data.desc,avatar:"YOU",color:"mint",time:Date.now(),read:false,replies:[]},...a]);flash("Notification created")}else if(dialog.mode==="edit"){setItems(a=>a.map(x=>x.id===dialog.item.id?{...x,title:data.title,desc:data.desc}:x));flash("Changes saved")}else{setItems(a=>a.map(x=>x.id===dialog.item.id?{...x,replies:[...(x.replies||[]),data.desc],read:true}:x));flash("Reply sent")}setDialog(null)};
 return <div className="app-shell" onClick={()=>menu&&setMenu(null)}><aside className="sidebar"><div className="brand"><span className="brand-mark"><i/><i/><i/></span>Notification center</div><nav><button><Icon name="inbox"/>Inbox</button><button className="active"><Icon name="bell"/>Notifications {!!unread&&<span className="nav-count">{unread}</span>}</button></nav><div className="workspace"><b>S</b><div><strong>Studio North</strong><small>12 members</small></div><button><Icon name="more"/></button></div></aside>
 <main><header className="topbar"><div className="mobile-brand"><span className="brand-mark"><i/><i/><i/></span>Notification center</div><label className="search"><Icon name="search" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notifications..."/>{query&&<button onClick={()=>setQuery("")}><Icon name="close" size={16}/></button>}</label><button className="help">?</button><div className="profile">LN</div></header>
 <section className="content"><div className="heading"><div><em>YOUR WORKSPACE</em><h1>Notifications</h1><p>Stay up to date with everything happening around your work.</p></div><div className="heading-actions"><button className="create" onClick={()=>setDialog({mode:"create"})}><Icon name="plus" size={17}/>Create</button><button className="mark-all" onClick={()=>{setItems(a=>a.map(x=>({...x,read:true})));flash("All caught up!")}} disabled={!unread}><Icon name="double" size={18}/>Mark all as read</button></div></div><div className="tabs"><button onClick={()=>setFilter("all")} className={filter==="all"?"active":""}>All <span>{items.length}</span></button><button onClick={()=>setFilter("unread")} className={filter==="unread"?"active":""}>Unread <span>{unread}</span></button></div>
 <div className="card">{!visible.length?<div className="empty"><div><Icon name="spark" size={28}/></div><h2>{query?"No matches found":"You're all caught up"}</h2><p>{query?"Try a different search term.":"There are no unread notifications right now."}</p><button onClick={()=>setDialog({mode:"create"})}>Create notification</button></div>:["Today","Yesterday","Earlier"].map(label=>groups[label]&&<section key={label}><div className="day"><span>{label}</span><i/></div>{groups[label].map(item=><article className={`notification ${item.read?"read":"unread"}`} key={item.id} onClick={()=>!item.read&&toggle(item.id)}><Visual item={item}/><div className="copy"><div><h2>{item.title}</h2><span>{ago(item.time)}</span></div><p>{item.desc}</p>{item.replies?.length>0&&<small><Icon name="reply" size={12}/>{item.replies.length} {item.replies.length===1?"reply":"replies"}</small>}</div><button className="quick-reply" onClick={e=>{e.stopPropagation();setDialog({mode:"reply",item})}} aria-label="Reply"><Icon name="reply" size={17}/></button><button className="read-toggle" onClick={e=>{e.stopPropagation();toggle(item.id)}} aria-label={item.read?"Mark as unread":"Mark as read"}><span className={item.read?"ring":"filled"}/></button><div className="menu-wrap"><button className="more" onClick={e=>{e.stopPropagation();setMenu(menu===item.id?null:item.id)}} aria-label="More options"><Icon name="more" size={19}/></button>{menu===item.id&&<div className="action-menu" onClick={e=>e.stopPropagation()}><button onClick={()=>{setDialog({mode:"reply",item});setMenu(null)}}><Icon name="reply"/>Reply</button><button onClick={()=>{setDialog({mode:"edit",item});setMenu(null)}}><Icon name="edit"/>Edit</button><button onClick={()=>{toggle(item.id);setMenu(null)}}><span className={item.read?"menu-dot filled":"menu-dot"}/>{item.read?"Mark unread":"Mark read"}</button><hr/><button className="danger" onClick={()=>remove(item.id)}><Icon name="trash"/>Delete</button></div>}</div></article>)}</section>)}</div></section></main>{dialog&&<Modal {...dialog} onClose={()=>setDialog(null)} onSave={save}/>} {toast&&<div className="toast"><Icon name="check" size={17}/>{toast}</div>}</div>}
