-- Run in a fresh Supabase project's SQL editor. This demo contains public sample data only.
create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique
);
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id),
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  status text not null default 'Pending' check (status in ('Completed','Processing','Pending','Cancelled')),
  created_at timestamptz not null default now()
);
create index orders_customer_id_idx on public.orders(customer_id);
alter table public.customers enable row level security;
alter table public.orders enable row level security;
-- Public read access is appropriate ONLY for this sample dataset.
-- Replace these policies with tenant/user-scoped policies before storing real customer data.
create policy "Read demo customers" on public.customers for select to anon, authenticated using (true);
create policy "Read demo orders" on public.orders for select to anon, authenticated using (true);
grant select on public.customers, public.orders to anon, authenticated;

create or replace function public.search_orders(search_query text default '')
returns table (id bigint, customer_id bigint, description text, amount numeric, status text, created_at timestamptz, customer_name text, customer_email text)
language sql stable security invoker set search_path = ''
as $$
  select o.id, o.customer_id, o.description, o.amount, o.status, o.created_at,
    c.name as customer_name, c.email as customer_email
  from public.orders o
  inner join public.customers c on o.customer_id = c.id
  where coalesce(trim(search_query), '') = ''
    or to_tsvector('english', o.id::text || ' ' || o.description || ' ' || c.name || ' ' || c.email)
       @@ websearch_to_tsquery('english', search_query)
  order by o.id desc;
$$;
revoke all on function public.search_orders(text) from public;
grant execute on function public.search_orders(text) to anon, authenticated;

insert into public.customers (name,email) values
 ('Olivia Rhye','olivia@acme.com'),('Phoenix Baker','phoenix@layers.design'),
 ('Lana Steiner','lana@sisyphus.com'),('Demi Wilkinson','demi@catalog.studio'),
 ('Drew Cano','drew@circooles.com'),('Natali Craig','natali@hourglass.app'),
 ('Orlando Diggs','orlando@command.com'),('Andi Lane','andi@quotient.co'),
 ('Kate Morrison','kate@cloudwatch.io'),('Lucy Bond','lucy@feather.design'),
 ('Noah Williams','noah@acme.com'),('James Wilson','james@layers.design');
insert into public.orders (id,customer_id,description,amount,status,created_at)
select 1048-i, (i%12)+1,
 (array['Premium workspace plan','Team collaboration bundle','Analytics add-on','Enterprise workspace plan','Design system subscription','Premium workspace plan','Team collaboration bundle','Cloud storage upgrade','Analytics add-on','Premium workspace plan','Enterprise workspace plan','Design system subscription'])[i%12+1],
 (array[249,149,79,599,129,249,149,49,79,249,599,129])[i%12+1],
 (array['Completed','Completed','Pending','Completed','Processing','Completed','Cancelled','Processing','Completed','Pending','Completed','Completed'])[i%12+1],
 '2026-09-07 16:24:00+00'::timestamptz - (i/8)*interval '1 day' - (i%8)*interval '1 hour'
from generate_series(0,47) i;
select setval(pg_get_serial_sequence('public.orders','id'), (select max(id) from public.orders));
