import { useState } from "react";
import toast from "react-hot-toast";
import { useAccounts, useCreateAccount, useSetOpeningBalance } from "../hooks/useAccounting";

export default function AccountSetupForms() {
  const { data: accounts = [] } = useAccounts();
  const [account, setAccount] = useState({ account_code: "", account_name: "", account_type: "asset", status: true });
  const [opening, setOpening] = useState({ account_id: "", amount: 0, as_of: new Date().toISOString().slice(0, 10) });
  const create = useCreateAccount({ onSuccess: () => { toast.success("Account created"); setAccount({ account_code: "", account_name: "", account_type: "asset", status: true }); }, onError: (e) => toast.error(e.message) });
  const postOpening = useSetOpeningBalance({ onSuccess: () => toast.success("Opening balance posted"), onError: (e) => toast.error(e.message) });
  return <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-4 dark:bg-slate-900"><h3 className="mb-3 font-semibold">Create Account</h3><div className="grid gap-2 sm:grid-cols-2"><input value={account.account_code} onChange={(e) => setAccount({ ...account, account_code: e.target.value })} placeholder="Account code" className="h-10 rounded border px-3" /><input value={account.account_name} onChange={(e) => setAccount({ ...account, account_name: e.target.value })} placeholder="Account name" className="h-10 rounded border px-3" /><select value={account.account_type} onChange={(e) => setAccount({ ...account, account_type: e.target.value })} className="h-10 rounded border px-3"><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="revenue">Revenue</option><option value="expense">Expense</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="inventory">Inventory</option><option value="accounts_receivable">Accounts Receivable</option><option value="accounts_payable">Accounts Payable</option><option value="cogs">COGS</option></select><button type="button" disabled={create.isPending} onClick={() => account.account_code.trim() && account.account_name.trim() ? create.mutate(account) : toast.error("Account code and account name are required")} className="h-10 rounded bg-blue-600 text-sm font-semibold text-white disabled:opacity-50">{create.isPending ? "Creating..." : "Create Account"}</button></div></div><div className="rounded-xl border bg-white p-4 dark:bg-slate-900"><h3 className="mb-3 font-semibold">Post Opening Balance</h3><div className="grid gap-2 sm:grid-cols-2"><select value={opening.account_id} onChange={(e) => setOpening({ ...opening, account_id: e.target.value })} className="h-10 rounded border px-3"><option value="">Select account</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.account_code} {a.account_name}</option>)}</select><input type="number" value={opening.amount} onChange={(e) => setOpening({ ...opening, amount: e.target.value })} placeholder="Amount" className="h-10 rounded border px-3" /><input type="date" value={opening.as_of} onChange={(e) => setOpening({ ...opening, as_of: e.target.value })} className="h-10 rounded border px-3" /><button type="button" disabled={postOpening.isPending} onClick={() => opening.account_id && Number(opening.amount) !== 0 ? postOpening.mutate(opening) : toast.error("Select an account and enter a non-zero opening balance")} className="h-10 rounded bg-emerald-600 text-sm font-semibold text-white disabled:opacity-50">{postOpening.isPending ? "Posting..." : "Post Opening Balance"}</button></div></div></div>;
}
