import { useState } from "react";
import toast from "react-hot-toast";
import { Plus, Trash2 } from "lucide-react";
import { useAccounts, usePostJournal } from "../hooks/useAccounting";

export default function JournalForm() {
  const { data: accounts = [] } = useAccounts();
  const [values, setValues] = useState({ transaction_date: new Date().toISOString().slice(0, 10), description: "", reference: "", items: [{ account_id: "", debit: 0, credit: 0 }, { account_id: "", debit: 0, credit: 0 }] });
  const mutation = usePostJournal({ onSuccess: () => { toast.success("Journal posted"); setValues({ ...values, description: "", reference: "", items: [{ account_id: "", debit: 0, credit: 0 }, { account_id: "", debit: 0, credit: 0 }] }); }, onError: (e) => toast.error(e.message) });
  const update = (index, field, value) => setValues({ ...values, items: values.items.map((item, i) => i === index ? { ...item, [field]: value } : item) });
  const debit = values.items.reduce((sum, item) => sum + Number(item.debit || 0), 0);
  const credit = values.items.reduce((sum, item) => sum + Number(item.credit || 0), 0);
  return <div className="rounded-xl border bg-white p-5 dark:bg-slate-900"><h2 className="mb-4 text-lg font-semibold">Manual Journal Entry</h2><div className="grid gap-3 sm:grid-cols-3"><input type="date" value={values.transaction_date} onChange={(e) => setValues({ ...values, transaction_date: e.target.value })} className="h-10 rounded border px-3" /><input value={values.reference} onChange={(e) => setValues({ ...values, reference: e.target.value })} placeholder="Reference" className="h-10 rounded border px-3" /><input value={values.description} onChange={(e) => setValues({ ...values, description: e.target.value })} placeholder="Description" className="h-10 rounded border px-3" /></div><div className="my-4 space-y-2">{values.items.map((item, index) => <div key={index} className="grid grid-cols-[1fr_130px_130px_40px] gap-2"><select value={item.account_id} onChange={(e) => update(index, "account_id", e.target.value)} className="h-10 rounded border px-2"><option value="">Select account</option>{accounts.filter((a) => a.status).map((a) => <option key={a.id} value={a.id}>{a.account_code} {a.account_name}</option>)}</select><input type="number" value={item.debit} onChange={(e) => update(index, "debit", e.target.value)} placeholder="Debit" className="h-10 rounded border px-2" /><input type="number" value={item.credit} onChange={(e) => update(index, "credit", e.target.value)} placeholder="Credit" className="h-10 rounded border px-2" /><button onClick={() => setValues({ ...values, items: values.items.filter((_, i) => i !== index) })} className="text-red-600"><Trash2 className="size-4" /></button></div>)}</div><div className="flex items-center justify-between"><button onClick={() => setValues({ ...values, items: [...values.items, { account_id: "", debit: 0, credit: 0 }] })} className="inline-flex items-center gap-2 text-sm text-blue-600"><Plus className="size-4" /> Add line</button><div className="flex gap-5 font-semibold"><span>Debit {debit.toFixed(2)}</span><span>Credit {credit.toFixed(2)}</span><button disabled={mutation.isPending || debit <= 0 || Math.abs(debit - credit) > 0.005} onClick={() => mutation.mutate(values)} className="rounded bg-blue-600 px-4 py-2 text-white disabled:opacity-50">Post Journal</button></div></div></div>;
}
