import { useEffect, useState } from 'react';
import * as api from '../lib/queries';
export default function RecordForm({kind,action,busy,sessions=[],faculty=[]}){
 const [open,setOpen]=useState(false),[programmes,setProgrammes]=useState([]),[catalogue,setCatalogue]=useState([]),[formError,setFormError]=useState('');
 useEffect(()=>{if(!open||!['offering','student'].includes(kind))return;let alive=true;Promise.all([api.getProgrammes(),kind==='offering'?api.getCatalogue():Promise.resolve([])]).then(([p,c])=>{if(alive){setProgrammes(p);setCatalogue(c);}}).catch(e=>{if(alive)setFormError(e.message);});return()=>{alive=false;};},[open,kind]);
 const fields={
 student:[['student_no','Student number'],['full_name','Full name'],['programme','Programme','programme']],
 programme:[['code','Programme code'],['name','Programme name']],
 faculty:[['full_name','Full name'],['employment_type','Employment type','employment'],['max_credits','Maximum credits','number'],['email','Account email (optional)','email']],
 offering:[['code','Course code'],['title','Course title'],['credits','Credits (1–6)','number'],['programme','Programme','programme'],['semester','Semester'],['section','Section'],['session_id','Academic session','session']],
 thesis:[['student_no','Student number'],['student_name','Student name'],['title','Thesis title'],['supervisor_id','Supervisor','faculty'],['deadline','Deadline','date']],
 conflict:[['kind','Issue type'],['message','Describe the issue']]
 }[kind];
 const titles={student:'Add student',programme:'Add programme',faculty:'Add faculty member',offering:'Add course offering',thesis:'Add thesis',conflict:'Report an issue'};
 return <div className="record-entry"><button type="button" className="secondary" onClick={()=>setOpen(!open)}>{open?'Close form':`+ ${titles[kind]}`}</button>{open&&<form className="record-form panel" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const record=Object.fromEntries(new FormData(form));setFormError('');action(async()=>{try{await api.createRecord(kind,record);setOpen(false);}catch(err){setFormError(err.message);throw err;}},`${titles[kind].replace('Add ','')} saved.`);}}><h3>{titles[kind]}</h3>{formError&&<p role="alert" className="red">{formError}</p>}{kind==='offering'&&catalogue.length>0&&<label>Use an existing course (optional)<select defaultValue="" onChange={e=>{const c=catalogue.find(c=>c.code===e.target.value);if(c){for(const k of ['code','title','credits'])e.target.form.elements.namedItem(k).value=c[k];}}}><option value="">Enter a new course below</option>{catalogue.map(c=><option key={c.code} value={c.code}>{c.code} ? {c.title}</option>)}</select></label>}<div className="record-fields">{fields.map(([key,label,type])=><label key={key}>{label}{type==='programme'?<select required name={key}><option value="">Select a programme</option>{programmes.map(p=><option key={p.id} value={p.code}>{p.code} ? {p.name}</option>)}</select>:type==='session'?<select required name={key}><option value="">Select a session</option>{sessions.filter(s=>s.status!=='approved').map(s=><option key={s.id} value={s.id}>{s.code} · {s.title}</option>)}</select>:type==='faculty'?<select required name={key}><option value="">Select a supervisor</option>{faculty.map(f=><option key={f.id} value={f.id}>{f.full_name}</option>)}</select>:type==='employment'?<select name={key}><option value="permanent">Permanent</option><option value="visiting">Visiting</option></select>:<input name={key} required={key!=='email'} type={type||'text'} min={type==='number'?1:undefined} max={key==='credits'?6:key==='max_credits'?60:undefined} defaultValue={key==='max_credits'?12:key==='credits'?3:key==='section'?'A':undefined} maxLength={500}/>}</label>)}</div>{kind==='offering'&&!sessions.length&&<p>Create an academic session in Semester planning first.</p>}<button disabled={busy||(kind==='offering'&&(!programmes.length||!sessions.some(s=>s.status!=='approved')))}>Save record</button></form>}</div>;
}
