import { supabase } from './supabase';
const client = () => { if (!supabase) throw new Error('Supabase is not configured.'); return supabase; };
export async function unwrap(request) { const { data, error } = await request; if (error) throw error; return data; }
export const getProfile = id => unwrap(client().from('profiles').select('*').eq('id', id).single());
export const getCourses = () => unwrap(client().from('course_offerings').select('id,semester,section,locked,session_id,courses(code,title,credits),programmes(code),allocations(id,faculty_id,assigned_credits,status,faculty(full_name,initials))').order('semester'));
export const getFaculty = () => unwrap(client().from('faculty').select('*,allocations(assigned_credits,course_offering_id)').order('full_name'));
export const getConflicts = () => unwrap(client().from('conflicts').select('*').eq('resolved', false).order('created_at', {ascending:false}));
export const getTheses = () => unwrap(client().from('theses').select('*,students(full_name,student_no),faculty(full_name)').order('deadline'));
export const getUsers = () => unwrap(client().from('profiles').select('*').order('full_name'));
export const updateMemberRole = (id,role) => unwrap(client().from('profiles').update({role}).eq('id',id).select().single());
export const inviteUser = form => unwrap(client().functions.invoke('invite-user', {body:form}));
export const allocateCourse = (offering,faculty) => unwrap(client().rpc('allocate_course',{p_offering_id:offering,p_faculty_id:faculty}));
export const resolveConflict = id => unwrap(client().from('conflicts').update({resolved:true,resolved_at:new Date().toISOString()}).eq('id',id).select().single());
export const getSessions = () => unwrap(client().from('academic_sessions').select('*').order('code',{ascending:false}));
export const saveSession = row => unwrap(client().from('academic_sessions').insert(row).select().single());
export const approveSession = id => unwrap(client().rpc('approve_session',{p_session_id:id}));
export const getHistory = () => unwrap(client().from('allocation_history').select('*').order('changed_at',{ascending:false}).limit(100));
export const getActivity = () => unwrap(client().from('activity_logs').select('*').order('created_at',{ascending:false}).limit(100));
export const updateCapacity = (id,max_credits) => unwrap(client().from('faculty').update({max_credits}).eq('id',id).select().single());
export const importAllocations = rows => unwrap(client().rpc('import_allocations',{p_rows:rows}));
export const createRecord = (kind,record) => unwrap(client().rpc('create_academic_record',{p_kind:kind,p_record:record}));
export const updateThesisStatus = (id,status) => unwrap(client().from('theses').update({status,updated_at:new Date().toISOString()}).eq('id',id).select().single());
export const loadExamples = () => unwrap(client().rpc('load_academic_examples'));
export const getProgrammes = () => unwrap(client().from('programmes').select('id,code,name').order('code'));
export const getCatalogue = () => unwrap(client().from('courses').select('code,title,credits').order('code'));
export const getStudents = () => unwrap(client().from('students').select('id,student_no,full_name,programmes(code)').order('student_no'));
export const editRecord = (kind,id,record) => unwrap(client().rpc('manage_academic_record',{p_kind:kind,p_id:id,p_operation:'update',p_record:record}));
export const deleteRecord = (kind,id) => unwrap(client().rpc('manage_academic_record',{p_kind:kind,p_id:id,p_operation:'delete',p_record:{}}));
export const getNotes = () => unwrap(client().from('teaching_notes').select('*').order('created_at',{ascending:false}));
export const saveNote = (id,row) => unwrap(id?client().from('teaching_notes').update(row).eq('id',id).select().single():client().from('teaching_notes').insert(row).select().single());
export const deleteNote = id => unwrap(client().from('teaching_notes').delete().eq('id',id).select().single());
export const getBatches = () => unwrap(client().from('batches').select('id,code,intake_year,semester,programmes(code,name)').order('code'));
