export const PERMISSIONS = Object.freeze({
  DASHBOARD: "dashboard.view",
  CUSTOMERS: "customers.view",
  SUPPLIERS: "suppliers.view",
  PRODUCTS: "products.view",
  PURCHASES: "purchases.view",
  STOCK: "stock.view",
  STOCK_ADJUST: "stock.adjust",
  POS: "pos.view",
  SALES: "sales.view",
  ACCOUNTS: "accounts.view",
  JOURNAL: "accounts.journal",
  EXPENSES: "expenses.view",
  PAYMENTS: "payments.view",
  REPORTS: "reports.view",
  USERS: "users.view",
  USERS_MANAGE: "users.manage",
  ROLES: "roles.view",
  ROLES_MANAGE: "roles.manage",
  SETTINGS: "settings.view",
});
