import { useEffect, useState } from "react";
import "./error-styles.css";
import { ErrorBoundary, withErrorBoundary } from "./ErrorBoundary.jsx";
import { clearErrorLog, getErrorLog, reportError, subscribeErrorLog } from "./errorReporting.js";

function Icon({ name, size = 18 }) {
  const paths = {
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
    bolt: <><path d="m13 2-9 12h7l-1 8 9-12h-7l1-8Z"/></>, chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/></>,
    bag: <><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></>, cursor: <><path d="m5 3 14 9-6 2-3 6L5 3Z"/><path d="m13 14 5 5"/></>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, terminal: <><rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3M13 15h4"/></>,
    trash: <><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v5M14 11v5"/></>, warning: <><path d="M10.3 3.5 2.4 18a2 2 0 0 0 1.8 3h15.6a2 2 0 0 0 1.8-3L13.7 3.5a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    activity: <path d="M3 12h4l2-7 4 14 2-7h6"/>, refresh: <><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6.1 9a7 7 0 0 1 11.2-2L20 12M4 12l2.7 5a7 7 0 0 0 11.2-2"/></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function CrashWidget({ title, description, icon }) { const [crash, setCrash] = useState(false); if (crash) throw new Error(`${title} failed to render: unexpected null in data payload`); return <article className="scenario-card"><div className="scenario-top"><span className="scenario-icon"><Icon name={icon}/></span><span className="status-badge"><i/>Healthy</span></div><h3>{title}</h3><p>{description}</p><button className="button danger-button" onClick={() => setCrash(true)}><Icon name="bolt" size={15}/>Simulate crash</button></article>; }
const SafeCrashWidget = withErrorBoundary(CrashWidget, { name: "isolated-widget" });
function StableWidget() { const [count,setCount]=useState(0); return <article className="scenario-card"><div className="scenario-top"><span className="scenario-icon blue"><Icon name="cursor"/></span><span className="status-badge"><i/>Interactive</span></div><h3>Independent control</h3><p>This card remains usable when a neighboring component fails.</p><button className="button secondary-button" onClick={()=>setCount(v=>v+1)}>Interaction count <strong>{count}</strong></button></article>; }
function AsyncWidget() { const [state,setState]=useState("idle"); function simulate(){setState("loading");setTimeout(()=>{const error=new Error("Async request failed: upstream service timed out");reportError(error,{boundary:"AsyncWidget · manual capture"});setState("caught")},650)} return <article className="scenario-card"><div className="scenario-top"><span className="scenario-icon amber"><Icon name="clock"/></span><span className={`status-badge ${state === "caught" ? "warning" : ""}`}><i/>{state === "caught" ? "Captured" : "Ready"}</span></div><h3>Async operation</h3><p>Explicit handling for errors outside React's render lifecycle.</p><button className="button secondary-button" disabled={state==="loading"} onClick={simulate}>{state === "loading" ? "Running simulation…" : "Test async capture"}</button></article>; }
function LogPanel(){const[,refresh]=useState(0);useEffect(()=>subscribeErrorLog(()=>refresh(n=>n+1)),[]);const entries=getErrorLog();return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Observability</span><h2>Event stream</h2><p>Captured exceptions ready for your monitoring provider.</p></div><button className="icon-button" onClick={clearErrorLog} disabled={!entries.length} aria-label="Clear event stream"><Icon name="trash"/></button></div><div className="table-head"><span>Event</span><span>Source</span><span>Time</span></div><div aria-live="polite">{!entries.length&&<div className="empty-state"><span><Icon name="activity" size={21}/></span><div><strong>No incidents detected</strong><small>Run a simulation to see captured events here.</small></div></div>}{entries.map(e=><div className="event-row" key={e.id}><span className="event-message"><i/><span><strong>{e.message}</strong><small>{e.id}</small></span></span><code>{e.context.boundary||"Unknown"}</code><time>{new Date(e.ts).toLocaleTimeString()}</time></div>)}</div></section>}
function AppShellFallback({error,reset}){return <main className="fatal-screen"><div className="fatal-card"><span className="fatal-icon"><Icon name="warning" size={28}/></span><span className="eyebrow">App shell protection</span><h1>The dashboard recovered safely.</h1><p>An unisolated component reached the final safety boundary. No permanent state was lost.</p><code>{error.message}</code><button className="button primary-button" onClick={reset}><Icon name="refresh" size={16}/>Restore dashboard</button></div></main>}
function GlobalCrashWidget(){const[crash,setCrash]=useState(false);if(crash)throw new Error("Unhandled component crash reached the app-shell boundary");return <button className="text-button" onClick={()=>setCrash(true)}><Icon name="warning" size={15}/>Test app-shell fallback</button>}
function Dashboard(){return <div className="app"><header className="topbar"><a className="brand" href="#top"><span><Icon name="shield" size={19}/></span>Analytics</a><div className="topbar-right"><span className="environment"><i/>Production sandbox</span><a className="docs-link" href="https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary" target="_blank" rel="noreferrer">Documentation ↗</a></div></header><main id="top" className="container"><section className="hero"><div><span className="eyebrow"><i/>System resilience playground</span><h1>Failure is inevitable.<br/><em>Downtime isn't.</em></h1><p>Explore how layered React error boundaries isolate failures, preserve healthy features, and keep the experience recoverable.</p></div><div className="health-card"><div className="health-ring"><Icon name="shield" size={27}/></div><div><span>System status</span><strong>All systems operational</strong><small>3 protection layers active</small></div></div></section><section className="section-heading"><div><span className="eyebrow">01 · Isolation testing</span><h2>Component-level scenarios</h2><p>Trigger controlled failures. Each card is protected independently.</p></div><span className="safe-note"><Icon name="shield" size={15}/>Safe to experiment</span></section><section className="scenario-grid"><SafeCrashWidget title="Revenue analytics" description="Protected chart and forecasting module." icon="chart"/><SafeCrashWidget title="Order pipeline" description="Protected commerce and fulfillment module." icon="bag"/><StableWidget/><AsyncWidget/></section><section className="shell-strip"><div><span className="shell-icon"><Icon name="terminal"/></span><span><strong>App-shell safety net</strong><small>The final boundary catches anything not protected locally.</small></span></div><GlobalCrashWidget/></section><LogPanel/></main><footer><span>Analytics · React Error Boundary System</span><span>Built for graceful failure</span></footer></div>}
export default function App(){return <ErrorBoundary name="app-shell" fallback={AppShellFallback}><Dashboard/></ErrorBoundary>}

