create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null check (char_length(text) between 1 and 500),
  sender text not null default 'Anonymous',
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists sender text not null default 'Anonymous';
alter table public.messages enable row level security;

drop policy if exists "Anyone can read messages" on public.messages;
create policy "Anyone can read messages" on public.messages for select using (true);
drop policy if exists "Anyone can send messages" on public.messages;
create policy "Anyone can send messages" on public.messages for insert with check (true);

do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.messages to anon, authenticated;
grant usage, select on sequence public.messages_id_seq to anon, authenticated;